package com.apps.catalog.entitymodel;

import java.util.Date;

/**
 * ProductCategory generated by MyEclipse Persistence Tools
 */

public class ProductCategory extends com.magic.entitymodel.GenericEntity
		implements java.io.Serializable {

	// Fields

	private String productCategoryId;

	private String productCategoryTypeId;

	private String primaryParentCategoryId;

	private String categoryName;

	private String description;

	private String longDescription;

	private String categoryImageUrl;

	private String linkOneImageUrl;

	private String linkTwoImageUrl;

	private String detailScreen;

	private String showInSelect;

	private Date lastUpdatedStamp;

	private Date lastUpdatedTxStamp;

	private Date createdStamp;

	private Date createdTxStamp;

	// Constructors

	/** default constructor */
	public ProductCategory() {
	}

	/** minimal constructor */
	public ProductCategory(String productCategoryId) {
		this.productCategoryId = productCategoryId;
	}

	/** full constructor */
	public ProductCategory(String productCategoryId,
			String productCategoryTypeId, String primaryParentCategoryId,
			String categoryName, String description, String longDescription,
			String categoryImageUrl, String linkOneImageUrl,
			String linkTwoImageUrl, String detailScreen, String showInSelect,
			Date lastUpdatedStamp, Date lastUpdatedTxStamp, Date createdStamp,
			Date createdTxStamp) {
		this.productCategoryId = productCategoryId;
		this.productCategoryTypeId = productCategoryTypeId;
		this.primaryParentCategoryId = primaryParentCategoryId;
		this.categoryName = categoryName;
		this.description = description;
		this.longDescription = longDescription;
		this.categoryImageUrl = categoryImageUrl;
		this.linkOneImageUrl = linkOneImageUrl;
		this.linkTwoImageUrl = linkTwoImageUrl;
		this.detailScreen = detailScreen;
		this.showInSelect = showInSelect;
		this.lastUpdatedStamp = lastUpdatedStamp;
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
		this.createdStamp = createdStamp;
		this.createdTxStamp = createdTxStamp;
	}

	// Property accessors

	public String getProductCategoryId() {
		return this.productCategoryId;
	}

	public void setProductCategoryId(String productCategoryId) {
		this.productCategoryId = productCategoryId;
	}

	public String getProductCategoryTypeId() {
		return this.productCategoryTypeId;
	}

	public void setProductCategoryTypeId(String productCategoryTypeId) {
		this.productCategoryTypeId = productCategoryTypeId;
	}

	public String getPrimaryParentCategoryId() {
		return this.primaryParentCategoryId;
	}

	public void setPrimaryParentCategoryId(String primaryParentCategoryId) {
		this.primaryParentCategoryId = primaryParentCategoryId;
	}

	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getLongDescription() {
		return this.longDescription;
	}

	public void setLongDescription(String longDescription) {
		this.longDescription = longDescription;
	}

	public String getCategoryImageUrl() {
		return this.categoryImageUrl;
	}

	public void setCategoryImageUrl(String categoryImageUrl) {
		this.categoryImageUrl = categoryImageUrl;
	}

	public String getLinkOneImageUrl() {
		return this.linkOneImageUrl;
	}

	public void setLinkOneImageUrl(String linkOneImageUrl) {
		this.linkOneImageUrl = linkOneImageUrl;
	}

	public String getLinkTwoImageUrl() {
		return this.linkTwoImageUrl;
	}

	public void setLinkTwoImageUrl(String linkTwoImageUrl) {
		this.linkTwoImageUrl = linkTwoImageUrl;
	}

	public String getDetailScreen() {
		return this.detailScreen;
	}

	public void setDetailScreen(String detailScreen) {
		this.detailScreen = detailScreen;
	}

	public String getShowInSelect() {
		return this.showInSelect;
	}

	public void setShowInSelect(String showInSelect) {
		this.showInSelect = showInSelect;
	}

	public Date getLastUpdatedStamp() {
		return this.lastUpdatedStamp;
	}

	public void setLastUpdatedStamp(Date lastUpdatedStamp) {
		this.lastUpdatedStamp = lastUpdatedStamp;
	}

	public Date getLastUpdatedTxStamp() {
		return this.lastUpdatedTxStamp;
	}

	public void setLastUpdatedTxStamp(Date lastUpdatedTxStamp) {
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
	}

	public Date getCreatedStamp() {
		return this.createdStamp;
	}

	public void setCreatedStamp(Date createdStamp) {
		this.createdStamp = createdStamp;
	}

	public Date getCreatedTxStamp() {
		return this.createdTxStamp;
	}

	public void setCreatedTxStamp(Date createdTxStamp) {
		this.createdTxStamp = createdTxStamp;
	}

}