package com.apps.catalog.entitymodel;

import java.util.Date;

/**
 * ProdCatalogCategory generated by MyEclipse Persistence Tools
 */

public class ProdCatalogCategory extends com.magic.entitymodel.GenericEntity
		implements java.io.Serializable {

	// Fields

	private ProdCatalogCategoryId id;

	private Date thruDate;

	private Long sequenceNum;

	private Date lastUpdatedStamp;

	private Date lastUpdatedTxStamp;

	private Date createdStamp;

	private Date createdTxStamp;

	// Constructors

	/** default constructor */
	public ProdCatalogCategory() {
	}

	/** minimal constructor */
	public ProdCatalogCategory(ProdCatalogCategoryId id) {
		this.id = id;
	}

	/** full constructor */
	public ProdCatalogCategory(ProdCatalogCategoryId id, Date thruDate,
			Long sequenceNum, Date lastUpdatedStamp, Date lastUpdatedTxStamp,
			Date createdStamp, Date createdTxStamp) {
		this.id = id;
		this.thruDate = thruDate;
		this.sequenceNum = sequenceNum;
		this.lastUpdatedStamp = lastUpdatedStamp;
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
		this.createdStamp = createdStamp;
		this.createdTxStamp = createdTxStamp;
	}

	// Property accessors

	public ProdCatalogCategoryId getId() {
		return this.id;
	}

	public void setId(ProdCatalogCategoryId id) {
		this.id = id;
	}

	public Date getThruDate() {
		return this.thruDate;
	}

	public void setThruDate(Date thruDate) {
		this.thruDate = thruDate;
	}

	public Long getSequenceNum() {
		return this.sequenceNum;
	}

	public void setSequenceNum(Long sequenceNum) {
		this.sequenceNum = sequenceNum;
	}

	public Date getLastUpdatedStamp() {
		return this.lastUpdatedStamp;
	}

	public void setLastUpdatedStamp(Date lastUpdatedStamp) {
		this.lastUpdatedStamp = lastUpdatedStamp;
	}

	public Date getLastUpdatedTxStamp() {
		return this.lastUpdatedTxStamp;
	}

	public void setLastUpdatedTxStamp(Date lastUpdatedTxStamp) {
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
	}

	public Date getCreatedStamp() {
		return this.createdStamp;
	}

	public void setCreatedStamp(Date createdStamp) {
		this.createdStamp = createdStamp;
	}

	public Date getCreatedTxStamp() {
		return this.createdTxStamp;
	}

	public void setCreatedTxStamp(Date createdTxStamp) {
		this.createdTxStamp = createdTxStamp;
	}

}