package com.apps.catalog.entitymodel;

import java.util.Date;

/**
 * ProdCatalog generated by MyEclipse Persistence Tools
 */

public class ProdCatalog extends com.magic.entitymodel.GenericEntity implements
		java.io.Serializable {

	// Fields

	private String prodCatalogId;

	private String catalogName;

	private String useQuickAdd;

	private String styleSheet;

	private String headerLogo;

	private String contentPathPrefix;

	private String templatePathPrefix;

	private String viewAllowPermReqd;

	private String purchaseAllowPermReqd;

	private Date lastUpdatedStamp;

	private Date lastUpdatedTxStamp;

	private Date createdStamp;

	private Date createdTxStamp;

	// Constructors

	/** default constructor */
	public ProdCatalog() {
	}

	/** minimal constructor */
	public ProdCatalog(String prodCatalogId) {
		this.prodCatalogId = prodCatalogId;
	}

	/** full constructor */
	public ProdCatalog(String prodCatalogId, String catalogName,
			String useQuickAdd, String styleSheet, String headerLogo,
			String contentPathPrefix, String templatePathPrefix,
			String viewAllowPermReqd, String purchaseAllowPermReqd,
			Date lastUpdatedStamp, Date lastUpdatedTxStamp, Date createdStamp,
			Date createdTxStamp) {
		this.prodCatalogId = prodCatalogId;
		this.catalogName = catalogName;
		this.useQuickAdd = useQuickAdd;
		this.styleSheet = styleSheet;
		this.headerLogo = headerLogo;
		this.contentPathPrefix = contentPathPrefix;
		this.templatePathPrefix = templatePathPrefix;
		this.viewAllowPermReqd = viewAllowPermReqd;
		this.purchaseAllowPermReqd = purchaseAllowPermReqd;
		this.lastUpdatedStamp = lastUpdatedStamp;
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
		this.createdStamp = createdStamp;
		this.createdTxStamp = createdTxStamp;
	}

	// Property accessors

	public String getProdCatalogId() {
		return this.prodCatalogId;
	}

	public void setProdCatalogId(String prodCatalogId) {
		this.prodCatalogId = prodCatalogId;
	}

	public String getCatalogName() {
		return this.catalogName;
	}

	public void setCatalogName(String catalogName) {
		this.catalogName = catalogName;
	}

	public String getUseQuickAdd() {
		return this.useQuickAdd;
	}

	public void setUseQuickAdd(String useQuickAdd) {
		this.useQuickAdd = useQuickAdd;
	}

	public String getStyleSheet() {
		return this.styleSheet;
	}

	public void setStyleSheet(String styleSheet) {
		this.styleSheet = styleSheet;
	}

	public String getHeaderLogo() {
		return this.headerLogo;
	}

	public void setHeaderLogo(String headerLogo) {
		this.headerLogo = headerLogo;
	}

	public String getContentPathPrefix() {
		return this.contentPathPrefix;
	}

	public void setContentPathPrefix(String contentPathPrefix) {
		this.contentPathPrefix = contentPathPrefix;
	}

	public String getTemplatePathPrefix() {
		return this.templatePathPrefix;
	}

	public void setTemplatePathPrefix(String templatePathPrefix) {
		this.templatePathPrefix = templatePathPrefix;
	}

	public String getViewAllowPermReqd() {
		return this.viewAllowPermReqd;
	}

	public void setViewAllowPermReqd(String viewAllowPermReqd) {
		this.viewAllowPermReqd = viewAllowPermReqd;
	}

	public String getPurchaseAllowPermReqd() {
		return this.purchaseAllowPermReqd;
	}

	public void setPurchaseAllowPermReqd(String purchaseAllowPermReqd) {
		this.purchaseAllowPermReqd = purchaseAllowPermReqd;
	}

	public Date getLastUpdatedStamp() {
		return this.lastUpdatedStamp;
	}

	public void setLastUpdatedStamp(Date lastUpdatedStamp) {
		this.lastUpdatedStamp = lastUpdatedStamp;
	}

	public Date getLastUpdatedTxStamp() {
		return this.lastUpdatedTxStamp;
	}

	public void setLastUpdatedTxStamp(Date lastUpdatedTxStamp) {
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
	}

	public Date getCreatedStamp() {
		return this.createdStamp;
	}

	public void setCreatedStamp(Date createdStamp) {
		this.createdStamp = createdStamp;
	}

	public Date getCreatedTxStamp() {
		return this.createdTxStamp;
	}

	public void setCreatedTxStamp(Date createdTxStamp) {
		this.createdTxStamp = createdTxStamp;
	}

}