package com.apps.catalog.entitymodel;

import java.util.Date;

/**
 * ProductCategoryMemberId generated by MyEclipse Persistence Tools
 */

public class ProductCategoryMemberId extends
		com.magic.entitymodel.GenericEntity implements java.io.Serializable {

	// Fields

	private String productCategoryId;

	private String productId;

	private Date fromDate;

	// Constructors

	/** default constructor */
	public ProductCategoryMemberId() {
	}

	/** full constructor */
	public ProductCategoryMemberId(String productCategoryId, String productId,
			Date fromDate) {
		this.productCategoryId = productCategoryId;
		this.productId = productId;
		this.fromDate = fromDate;
	}

	// Property accessors

	public String getProductCategoryId() {
		return this.productCategoryId;
	}

	public void setProductCategoryId(String productCategoryId) {
		this.productCategoryId = productCategoryId;
	}

	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProductCategoryMemberId))
			return false;
		ProductCategoryMemberId castOther = (ProductCategoryMemberId) other;

		return ((this.getProductCategoryId() == castOther
				.getProductCategoryId()) || (this.getProductCategoryId() != null
				&& castOther.getProductCategoryId() != null && this
				.getProductCategoryId()
				.equals(castOther.getProductCategoryId())))
				&& ((this.getProductId() == castOther.getProductId()) || (this
						.getProductId() != null
						&& castOther.getProductId() != null && this
						.getProductId().equals(castOther.getProductId())))
				&& ((this.getFromDate() == castOther.getFromDate()) || (this
						.getFromDate() != null
						&& castOther.getFromDate() != null && this
						.getFromDate().equals(castOther.getFromDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getProductCategoryId() == null ? 0 : this
						.getProductCategoryId().hashCode());
		result = 37 * result
				+ (getProductId() == null ? 0 : this.getProductId().hashCode());
		result = 37 * result
				+ (getFromDate() == null ? 0 : this.getFromDate().hashCode());
		return result;
	}

}