package com.apps.catalog.entitymodel;

import java.util.Date;

/**
 * ProdCatalogCategoryId generated by MyEclipse Persistence Tools
 */

public class ProdCatalogCategoryId extends com.magic.entitymodel.GenericEntity
		implements java.io.Serializable {

	// Fields

	private String prodCatalogId;

	private String productCategoryId;

	private String prodCatalogCategoryTypeId;

	private Date fromDate;

	// Constructors

	/** default constructor */
	public ProdCatalogCategoryId() {
	}

	/** full constructor */
	public ProdCatalogCategoryId(String prodCatalogId,
			String productCategoryId, String prodCatalogCategoryTypeId,
			Date fromDate) {
		this.prodCatalogId = prodCatalogId;
		this.productCategoryId = productCategoryId;
		this.prodCatalogCategoryTypeId = prodCatalogCategoryTypeId;
		this.fromDate = fromDate;
	}

	// Property accessors

	public String getProdCatalogId() {
		return this.prodCatalogId;
	}

	public void setProdCatalogId(String prodCatalogId) {
		this.prodCatalogId = prodCatalogId;
	}

	public String getProductCategoryId() {
		return this.productCategoryId;
	}

	public void setProductCategoryId(String productCategoryId) {
		this.productCategoryId = productCategoryId;
	}

	public String getProdCatalogCategoryTypeId() {
		return this.prodCatalogCategoryTypeId;
	}

	public void setProdCatalogCategoryTypeId(String prodCatalogCategoryTypeId) {
		this.prodCatalogCategoryTypeId = prodCatalogCategoryTypeId;
	}

	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProdCatalogCategoryId))
			return false;
		ProdCatalogCategoryId castOther = (ProdCatalogCategoryId) other;

		return ((this.getProdCatalogId() == castOther.getProdCatalogId()) || (this
				.getProdCatalogId() != null
				&& castOther.getProdCatalogId() != null && this
				.getProdCatalogId().equals(castOther.getProdCatalogId())))
				&& ((this.getProductCategoryId() == castOther
						.getProductCategoryId()) || (this
						.getProductCategoryId() != null
						&& castOther.getProductCategoryId() != null && this
						.getProductCategoryId().equals(
								castOther.getProductCategoryId())))
				&& ((this.getProdCatalogCategoryTypeId() == castOther
						.getProdCatalogCategoryTypeId()) || (this
						.getProdCatalogCategoryTypeId() != null
						&& castOther.getProdCatalogCategoryTypeId() != null && this
						.getProdCatalogCategoryTypeId().equals(
								castOther.getProdCatalogCategoryTypeId())))
				&& ((this.getFromDate() == castOther.getFromDate()) || (this
						.getFromDate() != null
						&& castOther.getFromDate() != null && this
						.getFromDate().equals(castOther.getFromDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getProdCatalogId() == null ? 0 : this.getProdCatalogId()
						.hashCode());
		result = 37
				* result
				+ (getProductCategoryId() == null ? 0 : this
						.getProductCategoryId().hashCode());
		result = 37
				* result
				+ (getProdCatalogCategoryTypeId() == null ? 0 : this
						.getProdCatalogCategoryTypeId().hashCode());
		result = 37 * result
				+ (getFromDate() == null ? 0 : this.getFromDate().hashCode());
		return result;
	}

}