package com.apps.catalog.entitymodel;

import java.util.Date;

/**
 * ProdCatalogCategoryType generated by MyEclipse Persistence Tools
 */

public class ProdCatalogCategoryType extends
		com.magic.entitymodel.GenericEntity implements java.io.Serializable {

	// Fields

	private String prodCatalogCategoryTypeId;

	private String description;

	private Date lastUpdatedStamp;

	private Date lastUpdatedTxStamp;

	private Date createdStamp;

	private Date createdTxStamp;

	// Constructors

	/** default constructor */
	public ProdCatalogCategoryType() {
	}

	/** minimal constructor */
	public ProdCatalogCategoryType(String prodCatalogCategoryTypeId) {
		this.prodCatalogCategoryTypeId = prodCatalogCategoryTypeId;
	}

	/** full constructor */
	public ProdCatalogCategoryType(String prodCatalogCategoryTypeId,
			String description, Date lastUpdatedStamp, Date lastUpdatedTxStamp,
			Date createdStamp, Date createdTxStamp) {
		this.prodCatalogCategoryTypeId = prodCatalogCategoryTypeId;
		this.description = description;
		this.lastUpdatedStamp = lastUpdatedStamp;
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
		this.createdStamp = createdStamp;
		this.createdTxStamp = createdTxStamp;
	}

	// Property accessors

	public String getProdCatalogCategoryTypeId() {
		return this.prodCatalogCategoryTypeId;
	}

	public void setProdCatalogCategoryTypeId(String prodCatalogCategoryTypeId) {
		this.prodCatalogCategoryTypeId = prodCatalogCategoryTypeId;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getLastUpdatedStamp() {
		return this.lastUpdatedStamp;
	}

	public void setLastUpdatedStamp(Date lastUpdatedStamp) {
		this.lastUpdatedStamp = lastUpdatedStamp;
	}

	public Date getLastUpdatedTxStamp() {
		return this.lastUpdatedTxStamp;
	}

	public void setLastUpdatedTxStamp(Date lastUpdatedTxStamp) {
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
	}

	public Date getCreatedStamp() {
		return this.createdStamp;
	}

	public void setCreatedStamp(Date createdStamp) {
		this.createdStamp = createdStamp;
	}

	public Date getCreatedTxStamp() {
		return this.createdTxStamp;
	}

	public void setCreatedTxStamp(Date createdTxStamp) {
		this.createdTxStamp = createdTxStamp;
	}

}