package com.apps.facility.entitymodel;

/**
 * FacilityRoleId generated by MyEclipse Persistence Tools
 */

public class FacilityRoleId extends com.magic.entitymodel.GenericEntity
		implements java.io.Serializable {

	// Fields

	private String facilityId;

	private String partyId;

	private String roleTypeId;

	// Constructors

	/** default constructor */
	public FacilityRoleId() {
	}

	/** full constructor */
	public FacilityRoleId(String facilityId, String partyId, String roleTypeId) {
		this.facilityId = facilityId;
		this.partyId = partyId;
		this.roleTypeId = roleTypeId;
	}

	// Property accessors

	public String getFacilityId() {
		return this.facilityId;
	}

	public void setFacilityId(String facilityId) {
		this.facilityId = facilityId;
	}

	public String getPartyId() {
		return this.partyId;
	}

	public void setPartyId(String partyId) {
		this.partyId = partyId;
	}

	public String getRoleTypeId() {
		return this.roleTypeId;
	}

	public void setRoleTypeId(String roleTypeId) {
		this.roleTypeId = roleTypeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FacilityRoleId))
			return false;
		FacilityRoleId castOther = (FacilityRoleId) other;

		return ((this.getFacilityId() == castOther.getFacilityId()) || (this
				.getFacilityId() != null
				&& castOther.getFacilityId() != null && this.getFacilityId()
				.equals(castOther.getFacilityId())))
				&& ((this.getPartyId() == castOther.getPartyId()) || (this
						.getPartyId() != null
						&& castOther.getPartyId() != null && this.getPartyId()
						.equals(castOther.getPartyId())))
				&& ((this.getRoleTypeId() == castOther.getRoleTypeId()) || (this
						.getRoleTypeId() != null
						&& castOther.getRoleTypeId() != null && this
						.getRoleTypeId().equals(castOther.getRoleTypeId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getFacilityId() == null ? 0 : this.getFacilityId()
						.hashCode());
		result = 37 * result
				+ (getPartyId() == null ? 0 : this.getPartyId().hashCode());
		result = 37
				* result
				+ (getRoleTypeId() == null ? 0 : this.getRoleTypeId()
						.hashCode());
		return result;
	}

}