package com.apps.facility.entitymodel;

import java.util.Date;

/**
 * FacilityContactMechPurposeId generated by MyEclipse Persistence Tools
 */

public class FacilityContactMechPurposeId extends
		com.magic.entitymodel.GenericEntity implements java.io.Serializable {

	// Fields

	private String facilityId;

	private String contactMechId;

	private String contactMechPurposeTypeId;

	private Date fromDate;

	// Constructors

	/** default constructor */
	public FacilityContactMechPurposeId() {
	}

	/** full constructor */
	public FacilityContactMechPurposeId(String facilityId,
			String contactMechId, String contactMechPurposeTypeId, Date fromDate) {
		this.facilityId = facilityId;
		this.contactMechId = contactMechId;
		this.contactMechPurposeTypeId = contactMechPurposeTypeId;
		this.fromDate = fromDate;
	}

	// Property accessors

	public String getFacilityId() {
		return this.facilityId;
	}

	public void setFacilityId(String facilityId) {
		this.facilityId = facilityId;
	}

	public String getContactMechId() {
		return this.contactMechId;
	}

	public void setContactMechId(String contactMechId) {
		this.contactMechId = contactMechId;
	}

	public String getContactMechPurposeTypeId() {
		return this.contactMechPurposeTypeId;
	}

	public void setContactMechPurposeTypeId(String contactMechPurposeTypeId) {
		this.contactMechPurposeTypeId = contactMechPurposeTypeId;
	}

	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FacilityContactMechPurposeId))
			return false;
		FacilityContactMechPurposeId castOther = (FacilityContactMechPurposeId) other;

		return ((this.getFacilityId() == castOther.getFacilityId()) || (this
				.getFacilityId() != null
				&& castOther.getFacilityId() != null && this.getFacilityId()
				.equals(castOther.getFacilityId())))
				&& ((this.getContactMechId() == castOther.getContactMechId()) || (this
						.getContactMechId() != null
						&& castOther.getContactMechId() != null && this
						.getContactMechId()
						.equals(castOther.getContactMechId())))
				&& ((this.getContactMechPurposeTypeId() == castOther
						.getContactMechPurposeTypeId()) || (this
						.getContactMechPurposeTypeId() != null
						&& castOther.getContactMechPurposeTypeId() != null && this
						.getContactMechPurposeTypeId().equals(
								castOther.getContactMechPurposeTypeId())))
				&& ((this.getFromDate() == castOther.getFromDate()) || (this
						.getFromDate() != null
						&& castOther.getFromDate() != null && this
						.getFromDate().equals(castOther.getFromDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getFacilityId() == null ? 0 : this.getFacilityId()
						.hashCode());
		result = 37
				* result
				+ (getContactMechId() == null ? 0 : this.getContactMechId()
						.hashCode());
		result = 37
				* result
				+ (getContactMechPurposeTypeId() == null ? 0 : this
						.getContactMechPurposeTypeId().hashCode());
		result = 37 * result
				+ (getFromDate() == null ? 0 : this.getFromDate().hashCode());
		return result;
	}

}