package com.apps.facility.entitymodel;

import java.util.Date;

/**
 * FacilityContactMechId generated by MyEclipse Persistence Tools
 */

public class FacilityContactMechId extends com.magic.entitymodel.GenericEntity
		implements java.io.Serializable {

	// Fields

	private String facilityId;

	private String contactMechId;

	private Date fromDate;

	// Constructors

	/** default constructor */
	public FacilityContactMechId() {
	}

	/** full constructor */
	public FacilityContactMechId(String facilityId, String contactMechId,
			Date fromDate) {
		this.facilityId = facilityId;
		this.contactMechId = contactMechId;
		this.fromDate = fromDate;
	}

	// Property accessors

	public String getFacilityId() {
		return this.facilityId;
	}

	public void setFacilityId(String facilityId) {
		this.facilityId = facilityId;
	}

	public String getContactMechId() {
		return this.contactMechId;
	}

	public void setContactMechId(String contactMechId) {
		this.contactMechId = contactMechId;
	}

	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FacilityContactMechId))
			return false;
		FacilityContactMechId castOther = (FacilityContactMechId) other;

		return ((this.getFacilityId() == castOther.getFacilityId()) || (this
				.getFacilityId() != null
				&& castOther.getFacilityId() != null && this.getFacilityId()
				.equals(castOther.getFacilityId())))
				&& ((this.getContactMechId() == castOther.getContactMechId()) || (this
						.getContactMechId() != null
						&& castOther.getContactMechId() != null && this
						.getContactMechId()
						.equals(castOther.getContactMechId())))
				&& ((this.getFromDate() == castOther.getFromDate()) || (this
						.getFromDate() != null
						&& castOther.getFromDate() != null && this
						.getFromDate().equals(castOther.getFromDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getFacilityId() == null ? 0 : this.getFacilityId()
						.hashCode());
		result = 37
				* result
				+ (getContactMechId() == null ? 0 : this.getContactMechId()
						.hashCode());
		result = 37 * result
				+ (getFromDate() == null ? 0 : this.getFromDate().hashCode());
		return result;
	}

}