package com.apps.facility.entitymodel;

import java.util.Date;

/**
 * Facility generated by MyEclipse Persistence Tools
 */

public class Facility extends com.magic.entitymodel.GenericEntity implements
		java.io.Serializable {

	// Fields

	private String facilityId;

	private String facilityTypeId;

	private String parentFacilityId;

	private String ownerPartyId;

	private String defaultInventoryItemTypeId;

	private String facilityName;

	private String primaryFacilityGroupId;

	private Long squareFootage;

	private String productStoreId;

	private Long defaultDaysToShip;

	private Date openedDate;

	private Date closedDate;

	private String description;

	private String defaultWeightUomId;

	private String geoPointId;

	private Date lastUpdatedStamp;

	private Date lastUpdatedTxStamp;

	private Date createdStamp;

	private Date createdTxStamp;

	// Constructors

	/** default constructor */
	public Facility() {
	}

	/** minimal constructor */
	public Facility(String facilityId) {
		this.facilityId = facilityId;
	}

	/** full constructor */
	public Facility(String facilityId, String facilityTypeId,
			String parentFacilityId, String ownerPartyId,
			String defaultInventoryItemTypeId, String facilityName,
			String primaryFacilityGroupId, Long squareFootage,
			String productStoreId, Long defaultDaysToShip, Date openedDate,
			Date closedDate, String description, String defaultWeightUomId,
			String geoPointId, Date lastUpdatedStamp, Date lastUpdatedTxStamp,
			Date createdStamp, Date createdTxStamp) {
		this.facilityId = facilityId;
		this.facilityTypeId = facilityTypeId;
		this.parentFacilityId = parentFacilityId;
		this.ownerPartyId = ownerPartyId;
		this.defaultInventoryItemTypeId = defaultInventoryItemTypeId;
		this.facilityName = facilityName;
		this.primaryFacilityGroupId = primaryFacilityGroupId;
		this.squareFootage = squareFootage;
		this.productStoreId = productStoreId;
		this.defaultDaysToShip = defaultDaysToShip;
		this.openedDate = openedDate;
		this.closedDate = closedDate;
		this.description = description;
		this.defaultWeightUomId = defaultWeightUomId;
		this.geoPointId = geoPointId;
		this.lastUpdatedStamp = lastUpdatedStamp;
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
		this.createdStamp = createdStamp;
		this.createdTxStamp = createdTxStamp;
	}

	// Property accessors

	public String getFacilityId() {
		return this.facilityId;
	}

	public void setFacilityId(String facilityId) {
		this.facilityId = facilityId;
	}

	public String getFacilityTypeId() {
		return this.facilityTypeId;
	}

	public void setFacilityTypeId(String facilityTypeId) {
		this.facilityTypeId = facilityTypeId;
	}

	public String getParentFacilityId() {
		return this.parentFacilityId;
	}

	public void setParentFacilityId(String parentFacilityId) {
		this.parentFacilityId = parentFacilityId;
	}

	public String getOwnerPartyId() {
		return this.ownerPartyId;
	}

	public void setOwnerPartyId(String ownerPartyId) {
		this.ownerPartyId = ownerPartyId;
	}

	public String getDefaultInventoryItemTypeId() {
		return this.defaultInventoryItemTypeId;
	}

	public void setDefaultInventoryItemTypeId(String defaultInventoryItemTypeId) {
		this.defaultInventoryItemTypeId = defaultInventoryItemTypeId;
	}

	public String getFacilityName() {
		return this.facilityName;
	}

	public void setFacilityName(String facilityName) {
		this.facilityName = facilityName;
	}

	public String getPrimaryFacilityGroupId() {
		return this.primaryFacilityGroupId;
	}

	public void setPrimaryFacilityGroupId(String primaryFacilityGroupId) {
		this.primaryFacilityGroupId = primaryFacilityGroupId;
	}

	public Long getSquareFootage() {
		return this.squareFootage;
	}

	public void setSquareFootage(Long squareFootage) {
		this.squareFootage = squareFootage;
	}

	public String getProductStoreId() {
		return this.productStoreId;
	}

	public void setProductStoreId(String productStoreId) {
		this.productStoreId = productStoreId;
	}

	public Long getDefaultDaysToShip() {
		return this.defaultDaysToShip;
	}

	public void setDefaultDaysToShip(Long defaultDaysToShip) {
		this.defaultDaysToShip = defaultDaysToShip;
	}

	public Date getOpenedDate() {
		return this.openedDate;
	}

	public void setOpenedDate(Date openedDate) {
		this.openedDate = openedDate;
	}

	public Date getClosedDate() {
		return this.closedDate;
	}

	public void setClosedDate(Date closedDate) {
		this.closedDate = closedDate;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getDefaultWeightUomId() {
		return this.defaultWeightUomId;
	}

	public void setDefaultWeightUomId(String defaultWeightUomId) {
		this.defaultWeightUomId = defaultWeightUomId;
	}

	public String getGeoPointId() {
		return this.geoPointId;
	}

	public void setGeoPointId(String geoPointId) {
		this.geoPointId = geoPointId;
	}

	public Date getLastUpdatedStamp() {
		return this.lastUpdatedStamp;
	}

	public void setLastUpdatedStamp(Date lastUpdatedStamp) {
		this.lastUpdatedStamp = lastUpdatedStamp;
	}

	public Date getLastUpdatedTxStamp() {
		return this.lastUpdatedTxStamp;
	}

	public void setLastUpdatedTxStamp(Date lastUpdatedTxStamp) {
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
	}

	public Date getCreatedStamp() {
		return this.createdStamp;
	}

	public void setCreatedStamp(Date createdStamp) {
		this.createdStamp = createdStamp;
	}

	public Date getCreatedTxStamp() {
		return this.createdTxStamp;
	}

	public void setCreatedTxStamp(Date createdTxStamp) {
		this.createdTxStamp = createdTxStamp;
	}

}