package com.apps.facility.entitymodel;

import java.util.Date;

/**
 * FacilityContactMechPurpose generated by MyEclipse Persistence Tools
 */

public class FacilityContactMechPurpose extends
		com.magic.entitymodel.GenericEntity implements java.io.Serializable {

	// Fields

	private FacilityContactMechPurposeId id;

	private Date thruDate;

	private Date lastUpdatedStamp;

	private Date lastUpdatedTxStamp;

	private Date createdStamp;

	private Date createdTxStamp;

	// Constructors

	/** default constructor */
	public FacilityContactMechPurpose() {
	}

	/** minimal constructor */
	public FacilityContactMechPurpose(FacilityContactMechPurposeId id) {
		this.id = id;
	}

	/** full constructor */
	public FacilityContactMechPurpose(FacilityContactMechPurposeId id,
			Date thruDate, Date lastUpdatedStamp, Date lastUpdatedTxStamp,
			Date createdStamp, Date createdTxStamp) {
		this.id = id;
		this.thruDate = thruDate;
		this.lastUpdatedStamp = lastUpdatedStamp;
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
		this.createdStamp = createdStamp;
		this.createdTxStamp = createdTxStamp;
	}

	// Property accessors

	public FacilityContactMechPurposeId getId() {
		return this.id;
	}

	public void setId(FacilityContactMechPurposeId id) {
		this.id = id;
	}

	public Date getThruDate() {
		return this.thruDate;
	}

	public void setThruDate(Date thruDate) {
		this.thruDate = thruDate;
	}

	public Date getLastUpdatedStamp() {
		return this.lastUpdatedStamp;
	}

	public void setLastUpdatedStamp(Date lastUpdatedStamp) {
		this.lastUpdatedStamp = lastUpdatedStamp;
	}

	public Date getLastUpdatedTxStamp() {
		return this.lastUpdatedTxStamp;
	}

	public void setLastUpdatedTxStamp(Date lastUpdatedTxStamp) {
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
	}

	public Date getCreatedStamp() {
		return this.createdStamp;
	}

	public void setCreatedStamp(Date createdStamp) {
		this.createdStamp = createdStamp;
	}

	public Date getCreatedTxStamp() {
		return this.createdTxStamp;
	}

	public void setCreatedTxStamp(Date createdTxStamp) {
		this.createdTxStamp = createdTxStamp;
	}

}