package com.apps.facility.entitymodel;

import java.util.Date;

/**
 * FacilityPartyId generated by MyEclipse Persistence Tools
 */

public class FacilityPartyId extends com.magic.entitymodel.GenericEntity
		implements java.io.Serializable {

	// Fields

	private String facilityId;

	private String partyId;

	private String roleTypeId;

	private Date fromDate;

	// Constructors

	/** default constructor */
	public FacilityPartyId() {
	}

	/** full constructor */
	public FacilityPartyId(String facilityId, String partyId,
			String roleTypeId, Date fromDate) {
		this.facilityId = facilityId;
		this.partyId = partyId;
		this.roleTypeId = roleTypeId;
		this.fromDate = fromDate;
	}

	// Property accessors

	public String getFacilityId() {
		return this.facilityId;
	}

	public void setFacilityId(String facilityId) {
		this.facilityId = facilityId;
	}

	public String getPartyId() {
		return this.partyId;
	}

	public void setPartyId(String partyId) {
		this.partyId = partyId;
	}

	public String getRoleTypeId() {
		return this.roleTypeId;
	}

	public void setRoleTypeId(String roleTypeId) {
		this.roleTypeId = roleTypeId;
	}

	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FacilityPartyId))
			return false;
		FacilityPartyId castOther = (FacilityPartyId) other;

		return ((this.getFacilityId() == castOther.getFacilityId()) || (this
				.getFacilityId() != null
				&& castOther.getFacilityId() != null && this.getFacilityId()
				.equals(castOther.getFacilityId())))
				&& ((this.getPartyId() == castOther.getPartyId()) || (this
						.getPartyId() != null
						&& castOther.getPartyId() != null && this.getPartyId()
						.equals(castOther.getPartyId())))
				&& ((this.getRoleTypeId() == castOther.getRoleTypeId()) || (this
						.getRoleTypeId() != null
						&& castOther.getRoleTypeId() != null && this
						.getRoleTypeId().equals(castOther.getRoleTypeId())))
				&& ((this.getFromDate() == castOther.getFromDate()) || (this
						.getFromDate() != null
						&& castOther.getFromDate() != null && this
						.getFromDate().equals(castOther.getFromDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getFacilityId() == null ? 0 : this.getFacilityId()
						.hashCode());
		result = 37 * result
				+ (getPartyId() == null ? 0 : this.getPartyId().hashCode());
		result = 37
				* result
				+ (getRoleTypeId() == null ? 0 : this.getRoleTypeId()
						.hashCode());
		result = 37 * result
				+ (getFromDate() == null ? 0 : this.getFromDate().hashCode());
		return result;
	}

}