package com.apps.facility.entitymodel;

import java.util.Date;

/**
 * InventoryItemStatusId generated by MyEclipse Persistence Tools
 */

public class InventoryItemStatusId extends com.magic.entitymodel.GenericEntity
		implements java.io.Serializable {

	// Fields

	private String inventoryItemId;

	private String statusId;

	private Date statusDatetime;

	// Constructors

	/** default constructor */
	public InventoryItemStatusId() {
	}

	/** full constructor */
	public InventoryItemStatusId(String inventoryItemId, String statusId,
			Date statusDatetime) {
		this.inventoryItemId = inventoryItemId;
		this.statusId = statusId;
		this.statusDatetime = statusDatetime;
	}

	// Property accessors

	public String getInventoryItemId() {
		return this.inventoryItemId;
	}

	public void setInventoryItemId(String inventoryItemId) {
		this.inventoryItemId = inventoryItemId;
	}

	public String getStatusId() {
		return this.statusId;
	}

	public void setStatusId(String statusId) {
		this.statusId = statusId;
	}

	public Date getStatusDatetime() {
		return this.statusDatetime;
	}

	public void setStatusDatetime(Date statusDatetime) {
		this.statusDatetime = statusDatetime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InventoryItemStatusId))
			return false;
		InventoryItemStatusId castOther = (InventoryItemStatusId) other;

		return ((this.getInventoryItemId() == castOther.getInventoryItemId()) || (this
				.getInventoryItemId() != null
				&& castOther.getInventoryItemId() != null && this
				.getInventoryItemId().equals(castOther.getInventoryItemId())))
				&& ((this.getStatusId() == castOther.getStatusId()) || (this
						.getStatusId() != null
						&& castOther.getStatusId() != null && this
						.getStatusId().equals(castOther.getStatusId())))
				&& ((this.getStatusDatetime() == castOther.getStatusDatetime()) || (this
						.getStatusDatetime() != null
						&& castOther.getStatusDatetime() != null && this
						.getStatusDatetime().equals(
								castOther.getStatusDatetime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getInventoryItemId() == null ? 0 : this.getInventoryItemId()
						.hashCode());
		result = 37 * result
				+ (getStatusId() == null ? 0 : this.getStatusId().hashCode());
		result = 37
				* result
				+ (getStatusDatetime() == null ? 0 : this.getStatusDatetime()
						.hashCode());
		return result;
	}

}