package com.apps.facility.entitymodel;

/**
 * InventoryItemDetailId generated by MyEclipse Persistence Tools
 */

public class InventoryItemDetailId extends com.magic.entitymodel.GenericEntity
		implements java.io.Serializable {

	// Fields

	private String inventoryItemId;

	private String inventoryItemDetailSeqId;

	// Constructors

	/** default constructor */
	public InventoryItemDetailId() {
	}

	/** full constructor */
	public InventoryItemDetailId(String inventoryItemId,
			String inventoryItemDetailSeqId) {
		this.inventoryItemId = inventoryItemId;
		this.inventoryItemDetailSeqId = inventoryItemDetailSeqId;
	}

	// Property accessors

	public String getInventoryItemId() {
		return this.inventoryItemId;
	}

	public void setInventoryItemId(String inventoryItemId) {
		this.inventoryItemId = inventoryItemId;
	}

	public String getInventoryItemDetailSeqId() {
		return this.inventoryItemDetailSeqId;
	}

	public void setInventoryItemDetailSeqId(String inventoryItemDetailSeqId) {
		this.inventoryItemDetailSeqId = inventoryItemDetailSeqId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InventoryItemDetailId))
			return false;
		InventoryItemDetailId castOther = (InventoryItemDetailId) other;

		return ((this.getInventoryItemId() == castOther.getInventoryItemId()) || (this
				.getInventoryItemId() != null
				&& castOther.getInventoryItemId() != null && this
				.getInventoryItemId().equals(castOther.getInventoryItemId())))
				&& ((this.getInventoryItemDetailSeqId() == castOther
						.getInventoryItemDetailSeqId()) || (this
						.getInventoryItemDetailSeqId() != null
						&& castOther.getInventoryItemDetailSeqId() != null && this
						.getInventoryItemDetailSeqId().equals(
								castOther.getInventoryItemDetailSeqId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getInventoryItemId() == null ? 0 : this.getInventoryItemId()
						.hashCode());
		result = 37
				* result
				+ (getInventoryItemDetailSeqId() == null ? 0 : this
						.getInventoryItemDetailSeqId().hashCode());
		return result;
	}

}