package com.apps.facility.entitymodel;

import java.util.Date;

/**
 * InventoryItemDetail generated by MyEclipse Persistence Tools
 */

public class InventoryItemDetail extends com.magic.entitymodel.GenericEntity
		implements java.io.Serializable {

	// Fields

	private InventoryItemDetailId id;

	private Date effectiveDate;

	private Double quantityOnHandDiff;

	private Double availableToPromiseDiff;

	private Double unitCost;

	private String orderId;

	private String orderItemSeqId;

	private String shipGroupSeqId;

	private String shipmentId;

	private String shipmentItemSeqId;

	private String returnId;

	private String returnItemSeqId;

	private String workEffortId;

	private String fixedAssetId;

	private String maintHistSeqId;

	private String itemIssuanceId;

	private String receiptId;

	private String physicalInventoryId;

	private String reasonEnumId;

	private String description;

	private Date lastUpdatedStamp;

	private Date lastUpdatedTxStamp;

	private Date createdStamp;

	private Date createdTxStamp;

	// Constructors

	/** default constructor */
	public InventoryItemDetail() {
	}

	/** minimal constructor */
	public InventoryItemDetail(InventoryItemDetailId id) {
		this.id = id;
	}

	/** full constructor */
	public InventoryItemDetail(InventoryItemDetailId id, Date effectiveDate,
			Double quantityOnHandDiff, Double availableToPromiseDiff,
			Double unitCost, String orderId, String orderItemSeqId,
			String shipGroupSeqId, String shipmentId, String shipmentItemSeqId,
			String returnId, String returnItemSeqId, String workEffortId,
			String fixedAssetId, String maintHistSeqId, String itemIssuanceId,
			String receiptId, String physicalInventoryId, String reasonEnumId,
			String description, Date lastUpdatedStamp, Date lastUpdatedTxStamp,
			Date createdStamp, Date createdTxStamp) {
		this.id = id;
		this.effectiveDate = effectiveDate;
		this.quantityOnHandDiff = quantityOnHandDiff;
		this.availableToPromiseDiff = availableToPromiseDiff;
		this.unitCost = unitCost;
		this.orderId = orderId;
		this.orderItemSeqId = orderItemSeqId;
		this.shipGroupSeqId = shipGroupSeqId;
		this.shipmentId = shipmentId;
		this.shipmentItemSeqId = shipmentItemSeqId;
		this.returnId = returnId;
		this.returnItemSeqId = returnItemSeqId;
		this.workEffortId = workEffortId;
		this.fixedAssetId = fixedAssetId;
		this.maintHistSeqId = maintHistSeqId;
		this.itemIssuanceId = itemIssuanceId;
		this.receiptId = receiptId;
		this.physicalInventoryId = physicalInventoryId;
		this.reasonEnumId = reasonEnumId;
		this.description = description;
		this.lastUpdatedStamp = lastUpdatedStamp;
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
		this.createdStamp = createdStamp;
		this.createdTxStamp = createdTxStamp;
	}

	// Property accessors

	public InventoryItemDetailId getId() {
		return this.id;
	}

	public void setId(InventoryItemDetailId id) {
		this.id = id;
	}

	public Date getEffectiveDate() {
		return this.effectiveDate;
	}

	public void setEffectiveDate(Date effectiveDate) {
		this.effectiveDate = effectiveDate;
	}

	public Double getQuantityOnHandDiff() {
		return this.quantityOnHandDiff;
	}

	public void setQuantityOnHandDiff(Double quantityOnHandDiff) {
		this.quantityOnHandDiff = quantityOnHandDiff;
	}

	public Double getAvailableToPromiseDiff() {
		return this.availableToPromiseDiff;
	}

	public void setAvailableToPromiseDiff(Double availableToPromiseDiff) {
		this.availableToPromiseDiff = availableToPromiseDiff;
	}

	public Double getUnitCost() {
		return this.unitCost;
	}

	public void setUnitCost(Double unitCost) {
		this.unitCost = unitCost;
	}

	public String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	public String getOrderItemSeqId() {
		return this.orderItemSeqId;
	}

	public void setOrderItemSeqId(String orderItemSeqId) {
		this.orderItemSeqId = orderItemSeqId;
	}

	public String getShipGroupSeqId() {
		return this.shipGroupSeqId;
	}

	public void setShipGroupSeqId(String shipGroupSeqId) {
		this.shipGroupSeqId = shipGroupSeqId;
	}

	public String getShipmentId() {
		return this.shipmentId;
	}

	public void setShipmentId(String shipmentId) {
		this.shipmentId = shipmentId;
	}

	public String getShipmentItemSeqId() {
		return this.shipmentItemSeqId;
	}

	public void setShipmentItemSeqId(String shipmentItemSeqId) {
		this.shipmentItemSeqId = shipmentItemSeqId;
	}

	public String getReturnId() {
		return this.returnId;
	}

	public void setReturnId(String returnId) {
		this.returnId = returnId;
	}

	public String getReturnItemSeqId() {
		return this.returnItemSeqId;
	}

	public void setReturnItemSeqId(String returnItemSeqId) {
		this.returnItemSeqId = returnItemSeqId;
	}

	public String getWorkEffortId() {
		return this.workEffortId;
	}

	public void setWorkEffortId(String workEffortId) {
		this.workEffortId = workEffortId;
	}

	public String getFixedAssetId() {
		return this.fixedAssetId;
	}

	public void setFixedAssetId(String fixedAssetId) {
		this.fixedAssetId = fixedAssetId;
	}

	public String getMaintHistSeqId() {
		return this.maintHistSeqId;
	}

	public void setMaintHistSeqId(String maintHistSeqId) {
		this.maintHistSeqId = maintHistSeqId;
	}

	public String getItemIssuanceId() {
		return this.itemIssuanceId;
	}

	public void setItemIssuanceId(String itemIssuanceId) {
		this.itemIssuanceId = itemIssuanceId;
	}

	public String getReceiptId() {
		return this.receiptId;
	}

	public void setReceiptId(String receiptId) {
		this.receiptId = receiptId;
	}

	public String getPhysicalInventoryId() {
		return this.physicalInventoryId;
	}

	public void setPhysicalInventoryId(String physicalInventoryId) {
		this.physicalInventoryId = physicalInventoryId;
	}

	public String getReasonEnumId() {
		return this.reasonEnumId;
	}

	public void setReasonEnumId(String reasonEnumId) {
		this.reasonEnumId = reasonEnumId;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getLastUpdatedStamp() {
		return this.lastUpdatedStamp;
	}

	public void setLastUpdatedStamp(Date lastUpdatedStamp) {
		this.lastUpdatedStamp = lastUpdatedStamp;
	}

	public Date getLastUpdatedTxStamp() {
		return this.lastUpdatedTxStamp;
	}

	public void setLastUpdatedTxStamp(Date lastUpdatedTxStamp) {
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
	}

	public Date getCreatedStamp() {
		return this.createdStamp;
	}

	public void setCreatedStamp(Date createdStamp) {
		this.createdStamp = createdStamp;
	}

	public Date getCreatedTxStamp() {
		return this.createdTxStamp;
	}

	public void setCreatedTxStamp(Date createdTxStamp) {
		this.createdTxStamp = createdTxStamp;
	}

}