package com.apps.facility.entitymodel;

import java.util.Date;

/**
 * InventoryItemStatus generated by MyEclipse Persistence Tools
 */

public class InventoryItemStatus extends com.magic.entitymodel.GenericEntity
		implements java.io.Serializable {

	// Fields

	private InventoryItemStatusId id;

	private Date statusEndDatetime;

	private String ownerPartyId;

	private String productId;

	private Date lastUpdatedStamp;

	private Date lastUpdatedTxStamp;

	private Date createdStamp;

	private Date createdTxStamp;

	// Constructors

	/** default constructor */
	public InventoryItemStatus() {
	}

	/** minimal constructor */
	public InventoryItemStatus(InventoryItemStatusId id) {
		this.id = id;
	}

	/** full constructor */
	public InventoryItemStatus(InventoryItemStatusId id,
			Date statusEndDatetime, String ownerPartyId, String productId,
			Date lastUpdatedStamp, Date lastUpdatedTxStamp, Date createdStamp,
			Date createdTxStamp) {
		this.id = id;
		this.statusEndDatetime = statusEndDatetime;
		this.ownerPartyId = ownerPartyId;
		this.productId = productId;
		this.lastUpdatedStamp = lastUpdatedStamp;
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
		this.createdStamp = createdStamp;
		this.createdTxStamp = createdTxStamp;
	}

	// Property accessors

	public InventoryItemStatusId getId() {
		return this.id;
	}

	public void setId(InventoryItemStatusId id) {
		this.id = id;
	}

	public Date getStatusEndDatetime() {
		return this.statusEndDatetime;
	}

	public void setStatusEndDatetime(Date statusEndDatetime) {
		this.statusEndDatetime = statusEndDatetime;
	}

	public String getOwnerPartyId() {
		return this.ownerPartyId;
	}

	public void setOwnerPartyId(String ownerPartyId) {
		this.ownerPartyId = ownerPartyId;
	}

	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	public Date getLastUpdatedStamp() {
		return this.lastUpdatedStamp;
	}

	public void setLastUpdatedStamp(Date lastUpdatedStamp) {
		this.lastUpdatedStamp = lastUpdatedStamp;
	}

	public Date getLastUpdatedTxStamp() {
		return this.lastUpdatedTxStamp;
	}

	public void setLastUpdatedTxStamp(Date lastUpdatedTxStamp) {
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
	}

	public Date getCreatedStamp() {
		return this.createdStamp;
	}

	public void setCreatedStamp(Date createdStamp) {
		this.createdStamp = createdStamp;
	}

	public Date getCreatedTxStamp() {
		return this.createdTxStamp;
	}

	public void setCreatedTxStamp(Date createdTxStamp) {
		this.createdTxStamp = createdTxStamp;
	}

}