package com.apps.facility.entitymodel;

import java.util.Date;

/**
 * InventoryItem generated by MyEclipse Persistence Tools
 */

public class InventoryItem extends com.magic.entitymodel.GenericEntity
		implements java.io.Serializable {

	// Fields

	private String inventoryItemId;

	private String inventoryItemTypeId;

	private String productId;

	private String partyId;

	private String ownerPartyId;

	private String statusId;

	private Date datetimeReceived;

	private Date datetimeManufactured;

	private Date expireDate;

	private String facilityId;

	private String containerId;

	private String lotId;

	private String uomId;

	private String binNumber;

	private String locationSeqId;

	private String comments;

	private Double quantityOnHandTotal;

	private Double availableToPromiseTotal;

	private Double quantityOnHand;

	private Double availableToPromise;

	private String serialNumber;

	private String softIdentifier;

	private String activationNumber;

	private Date activationValidThru;

	private Double unitCost;

	private String currencyUomId;

	private Date lastUpdatedStamp;

	private Date lastUpdatedTxStamp;

	private Date createdStamp;

	private Date createdTxStamp;

	// Constructors

	/** default constructor */
	public InventoryItem() {
	}

	/** minimal constructor */
	public InventoryItem(String inventoryItemId) {
		this.inventoryItemId = inventoryItemId;
	}

	/** full constructor */
	public InventoryItem(String inventoryItemId, String inventoryItemTypeId,
			String productId, String partyId, String ownerPartyId,
			String statusId, Date datetimeReceived, Date datetimeManufactured,
			Date expireDate, String facilityId, String containerId,
			String lotId, String uomId, String binNumber, String locationSeqId,
			String comments, Double quantityOnHandTotal,
			Double availableToPromiseTotal, Double quantityOnHand,
			Double availableToPromise, String serialNumber,
			String softIdentifier, String activationNumber,
			Date activationValidThru, Double unitCost, String currencyUomId,
			Date lastUpdatedStamp, Date lastUpdatedTxStamp, Date createdStamp,
			Date createdTxStamp) {
		this.inventoryItemId = inventoryItemId;
		this.inventoryItemTypeId = inventoryItemTypeId;
		this.productId = productId;
		this.partyId = partyId;
		this.ownerPartyId = ownerPartyId;
		this.statusId = statusId;
		this.datetimeReceived = datetimeReceived;
		this.datetimeManufactured = datetimeManufactured;
		this.expireDate = expireDate;
		this.facilityId = facilityId;
		this.containerId = containerId;
		this.lotId = lotId;
		this.uomId = uomId;
		this.binNumber = binNumber;
		this.locationSeqId = locationSeqId;
		this.comments = comments;
		this.quantityOnHandTotal = quantityOnHandTotal;
		this.availableToPromiseTotal = availableToPromiseTotal;
		this.quantityOnHand = quantityOnHand;
		this.availableToPromise = availableToPromise;
		this.serialNumber = serialNumber;
		this.softIdentifier = softIdentifier;
		this.activationNumber = activationNumber;
		this.activationValidThru = activationValidThru;
		this.unitCost = unitCost;
		this.currencyUomId = currencyUomId;
		this.lastUpdatedStamp = lastUpdatedStamp;
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
		this.createdStamp = createdStamp;
		this.createdTxStamp = createdTxStamp;
	}

	// Property accessors

	public String getInventoryItemId() {
		return this.inventoryItemId;
	}

	public void setInventoryItemId(String inventoryItemId) {
		this.inventoryItemId = inventoryItemId;
	}

	public String getInventoryItemTypeId() {
		return this.inventoryItemTypeId;
	}

	public void setInventoryItemTypeId(String inventoryItemTypeId) {
		this.inventoryItemTypeId = inventoryItemTypeId;
	}

	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	public String getPartyId() {
		return this.partyId;
	}

	public void setPartyId(String partyId) {
		this.partyId = partyId;
	}

	public String getOwnerPartyId() {
		return this.ownerPartyId;
	}

	public void setOwnerPartyId(String ownerPartyId) {
		this.ownerPartyId = ownerPartyId;
	}

	public String getStatusId() {
		return this.statusId;
	}

	public void setStatusId(String statusId) {
		this.statusId = statusId;
	}

	public Date getDatetimeReceived() {
		return this.datetimeReceived;
	}

	public void setDatetimeReceived(Date datetimeReceived) {
		this.datetimeReceived = datetimeReceived;
	}

	public Date getDatetimeManufactured() {
		return this.datetimeManufactured;
	}

	public void setDatetimeManufactured(Date datetimeManufactured) {
		this.datetimeManufactured = datetimeManufactured;
	}

	public Date getExpireDate() {
		return this.expireDate;
	}

	public void setExpireDate(Date expireDate) {
		this.expireDate = expireDate;
	}

	public String getFacilityId() {
		return this.facilityId;
	}

	public void setFacilityId(String facilityId) {
		this.facilityId = facilityId;
	}

	public String getContainerId() {
		return this.containerId;
	}

	public void setContainerId(String containerId) {
		this.containerId = containerId;
	}

	public String getLotId() {
		return this.lotId;
	}

	public void setLotId(String lotId) {
		this.lotId = lotId;
	}

	public String getUomId() {
		return this.uomId;
	}

	public void setUomId(String uomId) {
		this.uomId = uomId;
	}

	public String getBinNumber() {
		return this.binNumber;
	}

	public void setBinNumber(String binNumber) {
		this.binNumber = binNumber;
	}

	public String getLocationSeqId() {
		return this.locationSeqId;
	}

	public void setLocationSeqId(String locationSeqId) {
		this.locationSeqId = locationSeqId;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public Double getQuantityOnHandTotal() {
		return this.quantityOnHandTotal;
	}

	public void setQuantityOnHandTotal(Double quantityOnHandTotal) {
		this.quantityOnHandTotal = quantityOnHandTotal;
	}

	public Double getAvailableToPromiseTotal() {
		return this.availableToPromiseTotal;
	}

	public void setAvailableToPromiseTotal(Double availableToPromiseTotal) {
		this.availableToPromiseTotal = availableToPromiseTotal;
	}

	public Double getQuantityOnHand() {
		return this.quantityOnHand;
	}

	public void setQuantityOnHand(Double quantityOnHand) {
		this.quantityOnHand = quantityOnHand;
	}

	public Double getAvailableToPromise() {
		return this.availableToPromise;
	}

	public void setAvailableToPromise(Double availableToPromise) {
		this.availableToPromise = availableToPromise;
	}

	public String getSerialNumber() {
		return this.serialNumber;
	}

	public void setSerialNumber(String serialNumber) {
		this.serialNumber = serialNumber;
	}

	public String getSoftIdentifier() {
		return this.softIdentifier;
	}

	public void setSoftIdentifier(String softIdentifier) {
		this.softIdentifier = softIdentifier;
	}

	public String getActivationNumber() {
		return this.activationNumber;
	}

	public void setActivationNumber(String activationNumber) {
		this.activationNumber = activationNumber;
	}

	public Date getActivationValidThru() {
		return this.activationValidThru;
	}

	public void setActivationValidThru(Date activationValidThru) {
		this.activationValidThru = activationValidThru;
	}

	public Double getUnitCost() {
		return this.unitCost;
	}

	public void setUnitCost(Double unitCost) {
		this.unitCost = unitCost;
	}

	public String getCurrencyUomId() {
		return this.currencyUomId;
	}

	public void setCurrencyUomId(String currencyUomId) {
		this.currencyUomId = currencyUomId;
	}

	public Date getLastUpdatedStamp() {
		return this.lastUpdatedStamp;
	}

	public void setLastUpdatedStamp(Date lastUpdatedStamp) {
		this.lastUpdatedStamp = lastUpdatedStamp;
	}

	public Date getLastUpdatedTxStamp() {
		return this.lastUpdatedTxStamp;
	}

	public void setLastUpdatedTxStamp(Date lastUpdatedTxStamp) {
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
	}

	public Date getCreatedStamp() {
		return this.createdStamp;
	}

	public void setCreatedStamp(Date createdStamp) {
		this.createdStamp = createdStamp;
	}

	public Date getCreatedTxStamp() {
		return this.createdTxStamp;
	}

	public void setCreatedTxStamp(Date createdTxStamp) {
		this.createdTxStamp = createdTxStamp;
	}

}