package com.frm.security.entitymodel;

import java.util.Date;

/**
 * SecurityGroupPermission generated by MyEclipse Persistence Tools
 */

public class SecurityGroupPermission extends
		com.magic.entitymodel.GenericEntity implements java.io.Serializable {

	// Fields

	private SecurityGroupPermissionId id;

	private Date lastUpdatedStamp;

	private Date lastUpdatedTxStamp;

	private Date createdStamp;

	private Date createdTxStamp;

	// Constructors

	/** default constructor */
	public SecurityGroupPermission() {
	}

	/** minimal constructor */
	public SecurityGroupPermission(SecurityGroupPermissionId id) {
		this.id = id;
	}

	/** full constructor */
	public SecurityGroupPermission(SecurityGroupPermissionId id,
			Date lastUpdatedStamp, Date lastUpdatedTxStamp, Date createdStamp,
			Date createdTxStamp) {
		this.id = id;
		this.lastUpdatedStamp = lastUpdatedStamp;
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
		this.createdStamp = createdStamp;
		this.createdTxStamp = createdTxStamp;
	}

	// Property accessors

	public SecurityGroupPermissionId getId() {
		return this.id;
	}

	public void setId(SecurityGroupPermissionId id) {
		this.id = id;
	}

	public Date getLastUpdatedStamp() {
		return this.lastUpdatedStamp;
	}

	public void setLastUpdatedStamp(Date lastUpdatedStamp) {
		this.lastUpdatedStamp = lastUpdatedStamp;
	}

	public Date getLastUpdatedTxStamp() {
		return this.lastUpdatedTxStamp;
	}

	public void setLastUpdatedTxStamp(Date lastUpdatedTxStamp) {
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
	}

	public Date getCreatedStamp() {
		return this.createdStamp;
	}

	public void setCreatedStamp(Date createdStamp) {
		this.createdStamp = createdStamp;
	}

	public Date getCreatedTxStamp() {
		return this.createdTxStamp;
	}

	public void setCreatedTxStamp(Date createdTxStamp) {
		this.createdTxStamp = createdTxStamp;
	}

}