package com.frm.security.entitymodel;

import java.util.Date;

/**
 * UserLoginPasswordHistory generated by MyEclipse Persistence Tools
 */

public class UserLoginPasswordHistory extends
		com.magic.entitymodel.GenericEntity implements java.io.Serializable {

	// Fields

	private UserLoginPasswordHistoryId id;

	private Date thruDate;

	private String currentPassword;

	private Date lastUpdatedStamp;

	private Date lastUpdatedTxStamp;

	private Date createdStamp;

	private Date createdTxStamp;

	// Constructors

	/** default constructor */
	public UserLoginPasswordHistory() {
	}

	/** minimal constructor */
	public UserLoginPasswordHistory(UserLoginPasswordHistoryId id) {
		this.id = id;
	}

	/** full constructor */
	public UserLoginPasswordHistory(UserLoginPasswordHistoryId id,
			Date thruDate, String currentPassword, Date lastUpdatedStamp,
			Date lastUpdatedTxStamp, Date createdStamp, Date createdTxStamp) {
		this.id = id;
		this.thruDate = thruDate;
		this.currentPassword = currentPassword;
		this.lastUpdatedStamp = lastUpdatedStamp;
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
		this.createdStamp = createdStamp;
		this.createdTxStamp = createdTxStamp;
	}

	// Property accessors

	public UserLoginPasswordHistoryId getId() {
		return this.id;
	}

	public void setId(UserLoginPasswordHistoryId id) {
		this.id = id;
	}

	public Date getThruDate() {
		return this.thruDate;
	}

	public void setThruDate(Date thruDate) {
		this.thruDate = thruDate;
	}

	public String getCurrentPassword() {
		return this.currentPassword;
	}

	public void setCurrentPassword(String currentPassword) {
		this.currentPassword = currentPassword;
	}

	public Date getLastUpdatedStamp() {
		return this.lastUpdatedStamp;
	}

	public void setLastUpdatedStamp(Date lastUpdatedStamp) {
		this.lastUpdatedStamp = lastUpdatedStamp;
	}

	public Date getLastUpdatedTxStamp() {
		return this.lastUpdatedTxStamp;
	}

	public void setLastUpdatedTxStamp(Date lastUpdatedTxStamp) {
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
	}

	public Date getCreatedStamp() {
		return this.createdStamp;
	}

	public void setCreatedStamp(Date createdStamp) {
		this.createdStamp = createdStamp;
	}

	public Date getCreatedTxStamp() {
		return this.createdTxStamp;
	}

	public void setCreatedTxStamp(Date createdTxStamp) {
		this.createdTxStamp = createdTxStamp;
	}

}