package com.frm.security.entitymodel;

import java.util.Date;

/**
 * UserLoginHistory generated by MyEclipse Persistence Tools
 */

public class UserLoginHistory extends com.magic.entitymodel.GenericEntity
		implements java.io.Serializable {

	// Fields

	private UserLoginHistoryId id;

	private String visitId;

	private Date thruDate;

	private String passwordUsed;

	private String successfulLogin;

	private Date lastUpdatedStamp;

	private Date lastUpdatedTxStamp;

	private Date createdStamp;

	private Date createdTxStamp;

	private String partyId;

	// Constructors

	/** default constructor */
	public UserLoginHistory() {
	}

	/** minimal constructor */
	public UserLoginHistory(UserLoginHistoryId id) {
		this.id = id;
	}

	/** full constructor */
	public UserLoginHistory(UserLoginHistoryId id, String visitId,
			Date thruDate, String passwordUsed, String successfulLogin,
			Date lastUpdatedStamp, Date lastUpdatedTxStamp, Date createdStamp,
			Date createdTxStamp, String partyId) {
		this.id = id;
		this.visitId = visitId;
		this.thruDate = thruDate;
		this.passwordUsed = passwordUsed;
		this.successfulLogin = successfulLogin;
		this.lastUpdatedStamp = lastUpdatedStamp;
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
		this.createdStamp = createdStamp;
		this.createdTxStamp = createdTxStamp;
		this.partyId = partyId;
	}

	// Property accessors

	public UserLoginHistoryId getId() {
		return this.id;
	}

	public void setId(UserLoginHistoryId id) {
		this.id = id;
	}

	public String getVisitId() {
		return this.visitId;
	}

	public void setVisitId(String visitId) {
		this.visitId = visitId;
	}

	public Date getThruDate() {
		return this.thruDate;
	}

	public void setThruDate(Date thruDate) {
		this.thruDate = thruDate;
	}

	public String getPasswordUsed() {
		return this.passwordUsed;
	}

	public void setPasswordUsed(String passwordUsed) {
		this.passwordUsed = passwordUsed;
	}

	public String getSuccessfulLogin() {
		return this.successfulLogin;
	}

	public void setSuccessfulLogin(String successfulLogin) {
		this.successfulLogin = successfulLogin;
	}

	public Date getLastUpdatedStamp() {
		return this.lastUpdatedStamp;
	}

	public void setLastUpdatedStamp(Date lastUpdatedStamp) {
		this.lastUpdatedStamp = lastUpdatedStamp;
	}

	public Date getLastUpdatedTxStamp() {
		return this.lastUpdatedTxStamp;
	}

	public void setLastUpdatedTxStamp(Date lastUpdatedTxStamp) {
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
	}

	public Date getCreatedStamp() {
		return this.createdStamp;
	}

	public void setCreatedStamp(Date createdStamp) {
		this.createdStamp = createdStamp;
	}

	public Date getCreatedTxStamp() {
		return this.createdTxStamp;
	}

	public void setCreatedTxStamp(Date createdTxStamp) {
		this.createdTxStamp = createdTxStamp;
	}

	public String getPartyId() {
		return this.partyId;
	}

	public void setPartyId(String partyId) {
		this.partyId = partyId;
	}

}