package com.frm.security.entitymodel;

import java.util.Date;

/**
 * UserLogin generated by MyEclipse Persistence Tools
 */

public class UserLogin extends com.magic.entitymodel.GenericEntity implements
		java.io.Serializable {

	// Fields

	private String userLoginId;

	private String currentPassword;

	private String passwordHint;

	private String isSystem;

	private String enabled;

	private String hasLoggedOut;

	private String requirePasswordChange;

	private String lastCurrencyUom;

	private String lastLocale;

	private String lastTimeZone;

	private Date disabledDateTime;

	private Long successiveFailedLogins;

	private String userLdapDn;

	private Date lastUpdatedStamp;

	private Date lastUpdatedTxStamp;

	private Date createdStamp;

	private Date createdTxStamp;

	private String partyId;

	// Constructors

	/** default constructor */
	public UserLogin() {
	}

	/** minimal constructor */
	public UserLogin(String userLoginId) {
		this.userLoginId = userLoginId;
	}

	/** full constructor */
	public UserLogin(String userLoginId, String currentPassword,
			String passwordHint, String isSystem, String enabled,
			String hasLoggedOut, String requirePasswordChange,
			String lastCurrencyUom, String lastLocale, String lastTimeZone,
			Date disabledDateTime, Long successiveFailedLogins,
			String userLdapDn, Date lastUpdatedStamp, Date lastUpdatedTxStamp,
			Date createdStamp, Date createdTxStamp, String partyId) {
		this.userLoginId = userLoginId;
		this.currentPassword = currentPassword;
		this.passwordHint = passwordHint;
		this.isSystem = isSystem;
		this.enabled = enabled;
		this.hasLoggedOut = hasLoggedOut;
		this.requirePasswordChange = requirePasswordChange;
		this.lastCurrencyUom = lastCurrencyUom;
		this.lastLocale = lastLocale;
		this.lastTimeZone = lastTimeZone;
		this.disabledDateTime = disabledDateTime;
		this.successiveFailedLogins = successiveFailedLogins;
		this.userLdapDn = userLdapDn;
		this.lastUpdatedStamp = lastUpdatedStamp;
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
		this.createdStamp = createdStamp;
		this.createdTxStamp = createdTxStamp;
		this.partyId = partyId;
	}

	// Property accessors

	public String getUserLoginId() {
		return this.userLoginId;
	}

	public void setUserLoginId(String userLoginId) {
		this.userLoginId = userLoginId;
	}

	public String getCurrentPassword() {
		return this.currentPassword;
	}

	public void setCurrentPassword(String currentPassword) {
		this.currentPassword = currentPassword;
	}

	public String getPasswordHint() {
		return this.passwordHint;
	}

	public void setPasswordHint(String passwordHint) {
		this.passwordHint = passwordHint;
	}

	public String getIsSystem() {
		return this.isSystem;
	}

	public void setIsSystem(String isSystem) {
		this.isSystem = isSystem;
	}

	public String getEnabled() {
		return this.enabled;
	}

	public void setEnabled(String enabled) {
		this.enabled = enabled;
	}

	public String getHasLoggedOut() {
		return this.hasLoggedOut;
	}

	public void setHasLoggedOut(String hasLoggedOut) {
		this.hasLoggedOut = hasLoggedOut;
	}

	public String getRequirePasswordChange() {
		return this.requirePasswordChange;
	}

	public void setRequirePasswordChange(String requirePasswordChange) {
		this.requirePasswordChange = requirePasswordChange;
	}

	public String getLastCurrencyUom() {
		return this.lastCurrencyUom;
	}

	public void setLastCurrencyUom(String lastCurrencyUom) {
		this.lastCurrencyUom = lastCurrencyUom;
	}

	public String getLastLocale() {
		return this.lastLocale;
	}

	public void setLastLocale(String lastLocale) {
		this.lastLocale = lastLocale;
	}

	public String getLastTimeZone() {
		return this.lastTimeZone;
	}

	public void setLastTimeZone(String lastTimeZone) {
		this.lastTimeZone = lastTimeZone;
	}

	public Date getDisabledDateTime() {
		return this.disabledDateTime;
	}

	public void setDisabledDateTime(Date disabledDateTime) {
		this.disabledDateTime = disabledDateTime;
	}

	public Long getSuccessiveFailedLogins() {
		return this.successiveFailedLogins;
	}

	public void setSuccessiveFailedLogins(Long successiveFailedLogins) {
		this.successiveFailedLogins = successiveFailedLogins;
	}

	public String getUserLdapDn() {
		return this.userLdapDn;
	}

	public void setUserLdapDn(String userLdapDn) {
		this.userLdapDn = userLdapDn;
	}

	public Date getLastUpdatedStamp() {
		return this.lastUpdatedStamp;
	}

	public void setLastUpdatedStamp(Date lastUpdatedStamp) {
		this.lastUpdatedStamp = lastUpdatedStamp;
	}

	public Date getLastUpdatedTxStamp() {
		return this.lastUpdatedTxStamp;
	}

	public void setLastUpdatedTxStamp(Date lastUpdatedTxStamp) {
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
	}

	public Date getCreatedStamp() {
		return this.createdStamp;
	}

	public void setCreatedStamp(Date createdStamp) {
		this.createdStamp = createdStamp;
	}

	public Date getCreatedTxStamp() {
		return this.createdTxStamp;
	}

	public void setCreatedTxStamp(Date createdTxStamp) {
		this.createdTxStamp = createdTxStamp;
	}

	public String getPartyId() {
		return this.partyId;
	}

	public void setPartyId(String partyId) {
		this.partyId = partyId;
	}

}