package com.apps.order.entitymodel;

/**
 * OrderItemBillingId generated by MyEclipse Persistence Tools
 */

public class OrderItemBillingId extends com.magic.entitymodel.GenericEntity
		implements java.io.Serializable {

	// Fields

	private String orderId;

	private String orderItemSeqId;

	private String invoiceId;

	private String invoiceItemSeqId;

	// Constructors

	/** default constructor */
	public OrderItemBillingId() {
	}

	/** full constructor */
	public OrderItemBillingId(String orderId, String orderItemSeqId,
			String invoiceId, String invoiceItemSeqId) {
		this.orderId = orderId;
		this.orderItemSeqId = orderItemSeqId;
		this.invoiceId = invoiceId;
		this.invoiceItemSeqId = invoiceItemSeqId;
	}

	// Property accessors

	public String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	public String getOrderItemSeqId() {
		return this.orderItemSeqId;
	}

	public void setOrderItemSeqId(String orderItemSeqId) {
		this.orderItemSeqId = orderItemSeqId;
	}

	public String getInvoiceId() {
		return this.invoiceId;
	}

	public void setInvoiceId(String invoiceId) {
		this.invoiceId = invoiceId;
	}

	public String getInvoiceItemSeqId() {
		return this.invoiceItemSeqId;
	}

	public void setInvoiceItemSeqId(String invoiceItemSeqId) {
		this.invoiceItemSeqId = invoiceItemSeqId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrderItemBillingId))
			return false;
		OrderItemBillingId castOther = (OrderItemBillingId) other;

		return ((this.getOrderId() == castOther.getOrderId()) || (this
				.getOrderId() != null
				&& castOther.getOrderId() != null && this.getOrderId().equals(
				castOther.getOrderId())))
				&& ((this.getOrderItemSeqId() == castOther.getOrderItemSeqId()) || (this
						.getOrderItemSeqId() != null
						&& castOther.getOrderItemSeqId() != null && this
						.getOrderItemSeqId().equals(
								castOther.getOrderItemSeqId())))
				&& ((this.getInvoiceId() == castOther.getInvoiceId()) || (this
						.getInvoiceId() != null
						&& castOther.getInvoiceId() != null && this
						.getInvoiceId().equals(castOther.getInvoiceId())))
				&& ((this.getInvoiceItemSeqId() == castOther
						.getInvoiceItemSeqId()) || (this.getInvoiceItemSeqId() != null
						&& castOther.getInvoiceItemSeqId() != null && this
						.getInvoiceItemSeqId().equals(
								castOther.getInvoiceItemSeqId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getOrderId() == null ? 0 : this.getOrderId().hashCode());
		result = 37
				* result
				+ (getOrderItemSeqId() == null ? 0 : this.getOrderItemSeqId()
						.hashCode());
		result = 37 * result
				+ (getInvoiceId() == null ? 0 : this.getInvoiceId().hashCode());
		result = 37
				* result
				+ (getInvoiceItemSeqId() == null ? 0 : this
						.getInvoiceItemSeqId().hashCode());
		return result;
	}

}