package com.apps.order.entitymodel;

import java.util.Date;

/**
 * OrderItem generated by MyEclipse Persistence Tools
 */

public class OrderItem extends com.magic.entitymodel.GenericEntity implements
		java.io.Serializable {

	// Fields

	private OrderItemId id;

	private String externalId;

	private String orderItemTypeId;

	private String orderItemGroupSeqId;

	private String isItemGroupPrimary;

	private String fromInventoryItemId;

	private String budgetId;

	private String budgetItemSeqId;

	private String productId;

	private String productFeatureId;

	private String prodCatalogId;

	private String productCategoryId;

	private String isPromo;

	private String quoteId;

	private String quoteItemSeqId;

	private String shoppingListId;

	private String shoppingListItemSeqId;

	private String subscriptionId;

	private String deploymentId;

	private Double quantity;

	private Double cancelQuantity;

	private Double selectedAmount;

	private Double unitPrice;

	private Double unitListPrice;

	private Double unitAverageCost;

	private Double unitRecurringPrice;

	private String isModifiedPrice;

	private String recurringFreqUomId;

	private String itemDescription;

	private String comments;

	private String correspondingPoId;

	private String statusId;

	private String syncStatusId;

	private Date estimatedShipDate;

	private Date estimatedDeliveryDate;

	private Date autoCancelDate;

	private Date dontCancelSetDate;

	private String dontCancelSetUserLogin;

	private Date shipBeforeDate;

	private Date shipAfterDate;

	private Date cancelBackOrderDate;

	private String overrideGlAccountId;

	private String salesOpportunityId;

	private Date lastUpdatedStamp;

	private Date lastUpdatedTxStamp;

	private Date createdStamp;

	private Date createdTxStamp;

	// Constructors

	/** default constructor */
	public OrderItem() {
	}

	/** minimal constructor */
	public OrderItem(OrderItemId id) {
		this.id = id;
	}

	/** full constructor */
	public OrderItem(OrderItemId id, String externalId, String orderItemTypeId,
			String orderItemGroupSeqId, String isItemGroupPrimary,
			String fromInventoryItemId, String budgetId,
			String budgetItemSeqId, String productId, String productFeatureId,
			String prodCatalogId, String productCategoryId, String isPromo,
			String quoteId, String quoteItemSeqId, String shoppingListId,
			String shoppingListItemSeqId, String subscriptionId,
			String deploymentId, Double quantity, Double cancelQuantity,
			Double selectedAmount, Double unitPrice, Double unitListPrice,
			Double unitAverageCost, Double unitRecurringPrice,
			String isModifiedPrice, String recurringFreqUomId,
			String itemDescription, String comments, String correspondingPoId,
			String statusId, String syncStatusId, Date estimatedShipDate,
			Date estimatedDeliveryDate, Date autoCancelDate,
			Date dontCancelSetDate, String dontCancelSetUserLogin,
			Date shipBeforeDate, Date shipAfterDate, Date cancelBackOrderDate,
			String overrideGlAccountId, String salesOpportunityId,
			Date lastUpdatedStamp, Date lastUpdatedTxStamp, Date createdStamp,
			Date createdTxStamp) {
		this.id = id;
		this.externalId = externalId;
		this.orderItemTypeId = orderItemTypeId;
		this.orderItemGroupSeqId = orderItemGroupSeqId;
		this.isItemGroupPrimary = isItemGroupPrimary;
		this.fromInventoryItemId = fromInventoryItemId;
		this.budgetId = budgetId;
		this.budgetItemSeqId = budgetItemSeqId;
		this.productId = productId;
		this.productFeatureId = productFeatureId;
		this.prodCatalogId = prodCatalogId;
		this.productCategoryId = productCategoryId;
		this.isPromo = isPromo;
		this.quoteId = quoteId;
		this.quoteItemSeqId = quoteItemSeqId;
		this.shoppingListId = shoppingListId;
		this.shoppingListItemSeqId = shoppingListItemSeqId;
		this.subscriptionId = subscriptionId;
		this.deploymentId = deploymentId;
		this.quantity = quantity;
		this.cancelQuantity = cancelQuantity;
		this.selectedAmount = selectedAmount;
		this.unitPrice = unitPrice;
		this.unitListPrice = unitListPrice;
		this.unitAverageCost = unitAverageCost;
		this.unitRecurringPrice = unitRecurringPrice;
		this.isModifiedPrice = isModifiedPrice;
		this.recurringFreqUomId = recurringFreqUomId;
		this.itemDescription = itemDescription;
		this.comments = comments;
		this.correspondingPoId = correspondingPoId;
		this.statusId = statusId;
		this.syncStatusId = syncStatusId;
		this.estimatedShipDate = estimatedShipDate;
		this.estimatedDeliveryDate = estimatedDeliveryDate;
		this.autoCancelDate = autoCancelDate;
		this.dontCancelSetDate = dontCancelSetDate;
		this.dontCancelSetUserLogin = dontCancelSetUserLogin;
		this.shipBeforeDate = shipBeforeDate;
		this.shipAfterDate = shipAfterDate;
		this.cancelBackOrderDate = cancelBackOrderDate;
		this.overrideGlAccountId = overrideGlAccountId;
		this.salesOpportunityId = salesOpportunityId;
		this.lastUpdatedStamp = lastUpdatedStamp;
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
		this.createdStamp = createdStamp;
		this.createdTxStamp = createdTxStamp;
	}

	// Property accessors

	public OrderItemId getId() {
		return this.id;
	}

	public void setId(OrderItemId id) {
		this.id = id;
	}

	public String getExternalId() {
		return this.externalId;
	}

	public void setExternalId(String externalId) {
		this.externalId = externalId;
	}

	public String getOrderItemTypeId() {
		return this.orderItemTypeId;
	}

	public void setOrderItemTypeId(String orderItemTypeId) {
		this.orderItemTypeId = orderItemTypeId;
	}

	public String getOrderItemGroupSeqId() {
		return this.orderItemGroupSeqId;
	}

	public void setOrderItemGroupSeqId(String orderItemGroupSeqId) {
		this.orderItemGroupSeqId = orderItemGroupSeqId;
	}

	public String getIsItemGroupPrimary() {
		return this.isItemGroupPrimary;
	}

	public void setIsItemGroupPrimary(String isItemGroupPrimary) {
		this.isItemGroupPrimary = isItemGroupPrimary;
	}

	public String getFromInventoryItemId() {
		return this.fromInventoryItemId;
	}

	public void setFromInventoryItemId(String fromInventoryItemId) {
		this.fromInventoryItemId = fromInventoryItemId;
	}

	public String getBudgetId() {
		return this.budgetId;
	}

	public void setBudgetId(String budgetId) {
		this.budgetId = budgetId;
	}

	public String getBudgetItemSeqId() {
		return this.budgetItemSeqId;
	}

	public void setBudgetItemSeqId(String budgetItemSeqId) {
		this.budgetItemSeqId = budgetItemSeqId;
	}

	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	public String getProductFeatureId() {
		return this.productFeatureId;
	}

	public void setProductFeatureId(String productFeatureId) {
		this.productFeatureId = productFeatureId;
	}

	public String getProdCatalogId() {
		return this.prodCatalogId;
	}

	public void setProdCatalogId(String prodCatalogId) {
		this.prodCatalogId = prodCatalogId;
	}

	public String getProductCategoryId() {
		return this.productCategoryId;
	}

	public void setProductCategoryId(String productCategoryId) {
		this.productCategoryId = productCategoryId;
	}

	public String getIsPromo() {
		return this.isPromo;
	}

	public void setIsPromo(String isPromo) {
		this.isPromo = isPromo;
	}

	public String getQuoteId() {
		return this.quoteId;
	}

	public void setQuoteId(String quoteId) {
		this.quoteId = quoteId;
	}

	public String getQuoteItemSeqId() {
		return this.quoteItemSeqId;
	}

	public void setQuoteItemSeqId(String quoteItemSeqId) {
		this.quoteItemSeqId = quoteItemSeqId;
	}

	public String getShoppingListId() {
		return this.shoppingListId;
	}

	public void setShoppingListId(String shoppingListId) {
		this.shoppingListId = shoppingListId;
	}

	public String getShoppingListItemSeqId() {
		return this.shoppingListItemSeqId;
	}

	public void setShoppingListItemSeqId(String shoppingListItemSeqId) {
		this.shoppingListItemSeqId = shoppingListItemSeqId;
	}

	public String getSubscriptionId() {
		return this.subscriptionId;
	}

	public void setSubscriptionId(String subscriptionId) {
		this.subscriptionId = subscriptionId;
	}

	public String getDeploymentId() {
		return this.deploymentId;
	}

	public void setDeploymentId(String deploymentId) {
		this.deploymentId = deploymentId;
	}

	public Double getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Double quantity) {
		this.quantity = quantity;
	}

	public Double getCancelQuantity() {
		return this.cancelQuantity;
	}

	public void setCancelQuantity(Double cancelQuantity) {
		this.cancelQuantity = cancelQuantity;
	}

	public Double getSelectedAmount() {
		return this.selectedAmount;
	}

	public void setSelectedAmount(Double selectedAmount) {
		this.selectedAmount = selectedAmount;
	}

	public Double getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(Double unitPrice) {
		this.unitPrice = unitPrice;
	}

	public Double getUnitListPrice() {
		return this.unitListPrice;
	}

	public void setUnitListPrice(Double unitListPrice) {
		this.unitListPrice = unitListPrice;
	}

	public Double getUnitAverageCost() {
		return this.unitAverageCost;
	}

	public void setUnitAverageCost(Double unitAverageCost) {
		this.unitAverageCost = unitAverageCost;
	}

	public Double getUnitRecurringPrice() {
		return this.unitRecurringPrice;
	}

	public void setUnitRecurringPrice(Double unitRecurringPrice) {
		this.unitRecurringPrice = unitRecurringPrice;
	}

	public String getIsModifiedPrice() {
		return this.isModifiedPrice;
	}

	public void setIsModifiedPrice(String isModifiedPrice) {
		this.isModifiedPrice = isModifiedPrice;
	}

	public String getRecurringFreqUomId() {
		return this.recurringFreqUomId;
	}

	public void setRecurringFreqUomId(String recurringFreqUomId) {
		this.recurringFreqUomId = recurringFreqUomId;
	}

	public String getItemDescription() {
		return this.itemDescription;
	}

	public void setItemDescription(String itemDescription) {
		this.itemDescription = itemDescription;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public String getCorrespondingPoId() {
		return this.correspondingPoId;
	}

	public void setCorrespondingPoId(String correspondingPoId) {
		this.correspondingPoId = correspondingPoId;
	}

	public String getStatusId() {
		return this.statusId;
	}

	public void setStatusId(String statusId) {
		this.statusId = statusId;
	}

	public String getSyncStatusId() {
		return this.syncStatusId;
	}

	public void setSyncStatusId(String syncStatusId) {
		this.syncStatusId = syncStatusId;
	}

	public Date getEstimatedShipDate() {
		return this.estimatedShipDate;
	}

	public void setEstimatedShipDate(Date estimatedShipDate) {
		this.estimatedShipDate = estimatedShipDate;
	}

	public Date getEstimatedDeliveryDate() {
		return this.estimatedDeliveryDate;
	}

	public void setEstimatedDeliveryDate(Date estimatedDeliveryDate) {
		this.estimatedDeliveryDate = estimatedDeliveryDate;
	}

	public Date getAutoCancelDate() {
		return this.autoCancelDate;
	}

	public void setAutoCancelDate(Date autoCancelDate) {
		this.autoCancelDate = autoCancelDate;
	}

	public Date getDontCancelSetDate() {
		return this.dontCancelSetDate;
	}

	public void setDontCancelSetDate(Date dontCancelSetDate) {
		this.dontCancelSetDate = dontCancelSetDate;
	}

	public String getDontCancelSetUserLogin() {
		return this.dontCancelSetUserLogin;
	}

	public void setDontCancelSetUserLogin(String dontCancelSetUserLogin) {
		this.dontCancelSetUserLogin = dontCancelSetUserLogin;
	}

	public Date getShipBeforeDate() {
		return this.shipBeforeDate;
	}

	public void setShipBeforeDate(Date shipBeforeDate) {
		this.shipBeforeDate = shipBeforeDate;
	}

	public Date getShipAfterDate() {
		return this.shipAfterDate;
	}

	public void setShipAfterDate(Date shipAfterDate) {
		this.shipAfterDate = shipAfterDate;
	}

	public Date getCancelBackOrderDate() {
		return this.cancelBackOrderDate;
	}

	public void setCancelBackOrderDate(Date cancelBackOrderDate) {
		this.cancelBackOrderDate = cancelBackOrderDate;
	}

	public String getOverrideGlAccountId() {
		return this.overrideGlAccountId;
	}

	public void setOverrideGlAccountId(String overrideGlAccountId) {
		this.overrideGlAccountId = overrideGlAccountId;
	}

	public String getSalesOpportunityId() {
		return this.salesOpportunityId;
	}

	public void setSalesOpportunityId(String salesOpportunityId) {
		this.salesOpportunityId = salesOpportunityId;
	}

	public Date getLastUpdatedStamp() {
		return this.lastUpdatedStamp;
	}

	public void setLastUpdatedStamp(Date lastUpdatedStamp) {
		this.lastUpdatedStamp = lastUpdatedStamp;
	}

	public Date getLastUpdatedTxStamp() {
		return this.lastUpdatedTxStamp;
	}

	public void setLastUpdatedTxStamp(Date lastUpdatedTxStamp) {
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
	}

	public Date getCreatedStamp() {
		return this.createdStamp;
	}

	public void setCreatedStamp(Date createdStamp) {
		this.createdStamp = createdStamp;
	}

	public Date getCreatedTxStamp() {
		return this.createdTxStamp;
	}

	public void setCreatedTxStamp(Date createdTxStamp) {
		this.createdTxStamp = createdTxStamp;
	}

}