package com.apps.order.entitymodel;

import java.util.Date;

/**
 * OrderItemBilling generated by MyEclipse Persistence Tools
 */

public class OrderItemBilling extends com.magic.entitymodel.GenericEntity
		implements java.io.Serializable {

	// Fields

	private OrderItemBillingId id;

	private String itemIssuanceId;

	private String shipmentReceiptId;

	private Double quantity;

	private Double amount;

	private Date lastUpdatedStamp;

	private Date lastUpdatedTxStamp;

	private Date createdStamp;

	private Date createdTxStamp;

	// Constructors

	/** default constructor */
	public OrderItemBilling() {
	}

	/** minimal constructor */
	public OrderItemBilling(OrderItemBillingId id) {
		this.id = id;
	}

	/** full constructor */
	public OrderItemBilling(OrderItemBillingId id, String itemIssuanceId,
			String shipmentReceiptId, Double quantity, Double amount,
			Date lastUpdatedStamp, Date lastUpdatedTxStamp, Date createdStamp,
			Date createdTxStamp) {
		this.id = id;
		this.itemIssuanceId = itemIssuanceId;
		this.shipmentReceiptId = shipmentReceiptId;
		this.quantity = quantity;
		this.amount = amount;
		this.lastUpdatedStamp = lastUpdatedStamp;
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
		this.createdStamp = createdStamp;
		this.createdTxStamp = createdTxStamp;
	}

	// Property accessors

	public OrderItemBillingId getId() {
		return this.id;
	}

	public void setId(OrderItemBillingId id) {
		this.id = id;
	}

	public String getItemIssuanceId() {
		return this.itemIssuanceId;
	}

	public void setItemIssuanceId(String itemIssuanceId) {
		this.itemIssuanceId = itemIssuanceId;
	}

	public String getShipmentReceiptId() {
		return this.shipmentReceiptId;
	}

	public void setShipmentReceiptId(String shipmentReceiptId) {
		this.shipmentReceiptId = shipmentReceiptId;
	}

	public Double getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Double quantity) {
		this.quantity = quantity;
	}

	public Double getAmount() {
		return this.amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}

	public Date getLastUpdatedStamp() {
		return this.lastUpdatedStamp;
	}

	public void setLastUpdatedStamp(Date lastUpdatedStamp) {
		this.lastUpdatedStamp = lastUpdatedStamp;
	}

	public Date getLastUpdatedTxStamp() {
		return this.lastUpdatedTxStamp;
	}

	public void setLastUpdatedTxStamp(Date lastUpdatedTxStamp) {
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
	}

	public Date getCreatedStamp() {
		return this.createdStamp;
	}

	public void setCreatedStamp(Date createdStamp) {
		this.createdStamp = createdStamp;
	}

	public Date getCreatedTxStamp() {
		return this.createdTxStamp;
	}

	public void setCreatedTxStamp(Date createdTxStamp) {
		this.createdTxStamp = createdTxStamp;
	}

}