package com.apps.order.entitymodel;

/**
 * OrderItemId generated by MyEclipse Persistence Tools
 */

public class OrderItemId extends com.magic.entitymodel.GenericEntity implements
		java.io.Serializable {

	// Fields

	private String orderId;

	private String orderItemSeqId;

	// Constructors

	/** default constructor */
	public OrderItemId() {
	}

	/** full constructor */
	public OrderItemId(String orderId, String orderItemSeqId) {
		this.orderId = orderId;
		this.orderItemSeqId = orderItemSeqId;
	}

	// Property accessors

	public String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	public String getOrderItemSeqId() {
		return this.orderItemSeqId;
	}

	public void setOrderItemSeqId(String orderItemSeqId) {
		this.orderItemSeqId = orderItemSeqId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrderItemId))
			return false;
		OrderItemId castOther = (OrderItemId) other;

		return ((this.getOrderId() == castOther.getOrderId()) || (this
				.getOrderId() != null
				&& castOther.getOrderId() != null && this.getOrderId().equals(
				castOther.getOrderId())))
				&& ((this.getOrderItemSeqId() == castOther.getOrderItemSeqId()) || (this
						.getOrderItemSeqId() != null
						&& castOther.getOrderItemSeqId() != null && this
						.getOrderItemSeqId().equals(
								castOther.getOrderItemSeqId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getOrderId() == null ? 0 : this.getOrderId().hashCode());
		result = 37
				* result
				+ (getOrderItemSeqId() == null ? 0 : this.getOrderItemSeqId()
						.hashCode());
		return result;
	}

}