package com.magic.entitymodel;

// Generated 2011-6-16 23:59:51 by Hibernate Tools 3.4.0.CR1

/**
 * BuildUserMenusId generated by hbm2java
 */
public class BuildUserMenusId implements java.io.Serializable {

	private String userLoginId;
	private String menuId;

	public BuildUserMenusId() {
	}

	public BuildUserMenusId(String userLoginId, String menuId) {
		this.userLoginId = userLoginId;
		this.menuId = menuId;
	}

	public String getUserLoginId() {
		return this.userLoginId;
	}

	public void setUserLoginId(String userLoginId) {
		this.userLoginId = userLoginId;
	}

	public String getMenuId() {
		return this.menuId;
	}

	public void setMenuId(String menuId) {
		this.menuId = menuId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BuildUserMenusId))
			return false;
		BuildUserMenusId castOther = (BuildUserMenusId) other;

		return ((this.getUserLoginId() == castOther.getUserLoginId()) || (this
				.getUserLoginId() != null && castOther.getUserLoginId() != null && this
				.getUserLoginId().equals(castOther.getUserLoginId())))
				&& ((this.getMenuId() == castOther.getMenuId()) || (this
						.getMenuId() != null && castOther.getMenuId() != null && this
						.getMenuId().equals(castOther.getMenuId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getUserLoginId() == null ? 0 : this.getUserLoginId()
						.hashCode());
		result = 37 * result
				+ (getMenuId() == null ? 0 : this.getMenuId().hashCode());
		return result;
	}

}
