package com.apps.accounting.entitymodel;

import java.util.Date;

/**
 * FinAccountType generated by MyEclipse Persistence Tools
 */

public class FinAccountType extends com.magic.entitymodel.GenericEntity
		implements java.io.Serializable {

	// Fields

	private String finAccountTypeId;

	private String parentTypeId;

	private String replenishEnumId;

	private String isRefundable;

	private String hasTable;

	private String description;

	private Date lastUpdatedStamp;

	private Date lastUpdatedTxStamp;

	private Date createdStamp;

	private Date createdTxStamp;

	// Constructors

	/** default constructor */
	public FinAccountType() {
	}

	/** minimal constructor */
	public FinAccountType(String finAccountTypeId) {
		this.finAccountTypeId = finAccountTypeId;
	}

	/** full constructor */
	public FinAccountType(String finAccountTypeId, String parentTypeId,
			String replenishEnumId, String isRefundable, String hasTable,
			String description, Date lastUpdatedStamp, Date lastUpdatedTxStamp,
			Date createdStamp, Date createdTxStamp) {
		this.finAccountTypeId = finAccountTypeId;
		this.parentTypeId = parentTypeId;
		this.replenishEnumId = replenishEnumId;
		this.isRefundable = isRefundable;
		this.hasTable = hasTable;
		this.description = description;
		this.lastUpdatedStamp = lastUpdatedStamp;
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
		this.createdStamp = createdStamp;
		this.createdTxStamp = createdTxStamp;
	}

	// Property accessors

	public String getFinAccountTypeId() {
		return this.finAccountTypeId;
	}

	public void setFinAccountTypeId(String finAccountTypeId) {
		this.finAccountTypeId = finAccountTypeId;
	}

	public String getParentTypeId() {
		return this.parentTypeId;
	}

	public void setParentTypeId(String parentTypeId) {
		this.parentTypeId = parentTypeId;
	}

	public String getReplenishEnumId() {
		return this.replenishEnumId;
	}

	public void setReplenishEnumId(String replenishEnumId) {
		this.replenishEnumId = replenishEnumId;
	}

	public String getIsRefundable() {
		return this.isRefundable;
	}

	public void setIsRefundable(String isRefundable) {
		this.isRefundable = isRefundable;
	}

	public String getHasTable() {
		return this.hasTable;
	}

	public void setHasTable(String hasTable) {
		this.hasTable = hasTable;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getLastUpdatedStamp() {
		return this.lastUpdatedStamp;
	}

	public void setLastUpdatedStamp(Date lastUpdatedStamp) {
		this.lastUpdatedStamp = lastUpdatedStamp;
	}

	public Date getLastUpdatedTxStamp() {
		return this.lastUpdatedTxStamp;
	}

	public void setLastUpdatedTxStamp(Date lastUpdatedTxStamp) {
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
	}

	public Date getCreatedStamp() {
		return this.createdStamp;
	}

	public void setCreatedStamp(Date createdStamp) {
		this.createdStamp = createdStamp;
	}

	public Date getCreatedTxStamp() {
		return this.createdTxStamp;
	}

	public void setCreatedTxStamp(Date createdTxStamp) {
		this.createdTxStamp = createdTxStamp;
	}

}