package com.apps.accounting.entitymodel;

import java.util.Date;

/**
 * FinAccount generated by MyEclipse Persistence Tools
 */

public class FinAccount extends com.magic.entitymodel.GenericEntity implements
		java.io.Serializable {

	// Fields

	private String finAccountId;

	private String finAccountTypeId;

	private String statusId;

	private String finAccountName;

	private String finAccountCode;

	private String finAccountPin;

	private String currencyUomId;

	private String organizationPartyId;

	private String ownerPartyId;

	private String postToGlAccountId;

	private Date fromDate;

	private Date thruDate;

	private String isRefundable;

	private String replenishPaymentId;

	private Double replenishLevel;

	private Double actualBalance;

	private Double availableBalance;

	private Date lastUpdatedStamp;

	private Date lastUpdatedTxStamp;

	private Date createdStamp;

	private Date createdTxStamp;

	// Constructors

	/** default constructor */
	public FinAccount() {
	}

	/** minimal constructor */
	public FinAccount(String finAccountId) {
		this.finAccountId = finAccountId;
	}

	/** full constructor */
	public FinAccount(String finAccountId, String finAccountTypeId,
			String statusId, String finAccountName, String finAccountCode,
			String finAccountPin, String currencyUomId,
			String organizationPartyId, String ownerPartyId,
			String postToGlAccountId, Date fromDate, Date thruDate,
			String isRefundable, String replenishPaymentId,
			Double replenishLevel, Double actualBalance,
			Double availableBalance, Date lastUpdatedStamp,
			Date lastUpdatedTxStamp, Date createdStamp, Date createdTxStamp) {
		this.finAccountId = finAccountId;
		this.finAccountTypeId = finAccountTypeId;
		this.statusId = statusId;
		this.finAccountName = finAccountName;
		this.finAccountCode = finAccountCode;
		this.finAccountPin = finAccountPin;
		this.currencyUomId = currencyUomId;
		this.organizationPartyId = organizationPartyId;
		this.ownerPartyId = ownerPartyId;
		this.postToGlAccountId = postToGlAccountId;
		this.fromDate = fromDate;
		this.thruDate = thruDate;
		this.isRefundable = isRefundable;
		this.replenishPaymentId = replenishPaymentId;
		this.replenishLevel = replenishLevel;
		this.actualBalance = actualBalance;
		this.availableBalance = availableBalance;
		this.lastUpdatedStamp = lastUpdatedStamp;
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
		this.createdStamp = createdStamp;
		this.createdTxStamp = createdTxStamp;
	}

	// Property accessors

	public String getFinAccountId() {
		return this.finAccountId;
	}

	public void setFinAccountId(String finAccountId) {
		this.finAccountId = finAccountId;
	}

	public String getFinAccountTypeId() {
		return this.finAccountTypeId;
	}

	public void setFinAccountTypeId(String finAccountTypeId) {
		this.finAccountTypeId = finAccountTypeId;
	}

	public String getStatusId() {
		return this.statusId;
	}

	public void setStatusId(String statusId) {
		this.statusId = statusId;
	}

	public String getFinAccountName() {
		return this.finAccountName;
	}

	public void setFinAccountName(String finAccountName) {
		this.finAccountName = finAccountName;
	}

	public String getFinAccountCode() {
		return this.finAccountCode;
	}

	public void setFinAccountCode(String finAccountCode) {
		this.finAccountCode = finAccountCode;
	}

	public String getFinAccountPin() {
		return this.finAccountPin;
	}

	public void setFinAccountPin(String finAccountPin) {
		this.finAccountPin = finAccountPin;
	}

	public String getCurrencyUomId() {
		return this.currencyUomId;
	}

	public void setCurrencyUomId(String currencyUomId) {
		this.currencyUomId = currencyUomId;
	}

	public String getOrganizationPartyId() {
		return this.organizationPartyId;
	}

	public void setOrganizationPartyId(String organizationPartyId) {
		this.organizationPartyId = organizationPartyId;
	}

	public String getOwnerPartyId() {
		return this.ownerPartyId;
	}

	public void setOwnerPartyId(String ownerPartyId) {
		this.ownerPartyId = ownerPartyId;
	}

	public String getPostToGlAccountId() {
		return this.postToGlAccountId;
	}

	public void setPostToGlAccountId(String postToGlAccountId) {
		this.postToGlAccountId = postToGlAccountId;
	}

	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	public Date getThruDate() {
		return this.thruDate;
	}

	public void setThruDate(Date thruDate) {
		this.thruDate = thruDate;
	}

	public String getIsRefundable() {
		return this.isRefundable;
	}

	public void setIsRefundable(String isRefundable) {
		this.isRefundable = isRefundable;
	}

	public String getReplenishPaymentId() {
		return this.replenishPaymentId;
	}

	public void setReplenishPaymentId(String replenishPaymentId) {
		this.replenishPaymentId = replenishPaymentId;
	}

	public Double getReplenishLevel() {
		return this.replenishLevel;
	}

	public void setReplenishLevel(Double replenishLevel) {
		this.replenishLevel = replenishLevel;
	}

	public Double getActualBalance() {
		return this.actualBalance;
	}

	public void setActualBalance(Double actualBalance) {
		this.actualBalance = actualBalance;
	}

	public Double getAvailableBalance() {
		return this.availableBalance;
	}

	public void setAvailableBalance(Double availableBalance) {
		this.availableBalance = availableBalance;
	}

	public Date getLastUpdatedStamp() {
		return this.lastUpdatedStamp;
	}

	public void setLastUpdatedStamp(Date lastUpdatedStamp) {
		this.lastUpdatedStamp = lastUpdatedStamp;
	}

	public Date getLastUpdatedTxStamp() {
		return this.lastUpdatedTxStamp;
	}

	public void setLastUpdatedTxStamp(Date lastUpdatedTxStamp) {
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
	}

	public Date getCreatedStamp() {
		return this.createdStamp;
	}

	public void setCreatedStamp(Date createdStamp) {
		this.createdStamp = createdStamp;
	}

	public Date getCreatedTxStamp() {
		return this.createdTxStamp;
	}

	public void setCreatedTxStamp(Date createdTxStamp) {
		this.createdTxStamp = createdTxStamp;
	}

}