package com.apps.accounting.entitymodel;

/**
 * PaymentGlAccountTypeMapId generated by MyEclipse Persistence Tools
 */

public class PaymentGlAccountTypeMapId extends
		com.magic.entitymodel.GenericEntity implements java.io.Serializable {

	// Fields

	private String paymentTypeId;

	private String organizationPartyId;

	// Constructors

	/** default constructor */
	public PaymentGlAccountTypeMapId() {
	}

	/** full constructor */
	public PaymentGlAccountTypeMapId(String paymentTypeId,
			String organizationPartyId) {
		this.paymentTypeId = paymentTypeId;
		this.organizationPartyId = organizationPartyId;
	}

	// Property accessors

	public String getPaymentTypeId() {
		return this.paymentTypeId;
	}

	public void setPaymentTypeId(String paymentTypeId) {
		this.paymentTypeId = paymentTypeId;
	}

	public String getOrganizationPartyId() {
		return this.organizationPartyId;
	}

	public void setOrganizationPartyId(String organizationPartyId) {
		this.organizationPartyId = organizationPartyId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PaymentGlAccountTypeMapId))
			return false;
		PaymentGlAccountTypeMapId castOther = (PaymentGlAccountTypeMapId) other;

		return ((this.getPaymentTypeId() == castOther.getPaymentTypeId()) || (this
				.getPaymentTypeId() != null
				&& castOther.getPaymentTypeId() != null && this
				.getPaymentTypeId().equals(castOther.getPaymentTypeId())))
				&& ((this.getOrganizationPartyId() == castOther
						.getOrganizationPartyId()) || (this
						.getOrganizationPartyId() != null
						&& castOther.getOrganizationPartyId() != null && this
						.getOrganizationPartyId().equals(
								castOther.getOrganizationPartyId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getPaymentTypeId() == null ? 0 : this.getPaymentTypeId()
						.hashCode());
		result = 37
				* result
				+ (getOrganizationPartyId() == null ? 0 : this
						.getOrganizationPartyId().hashCode());
		return result;
	}

}