package com.apps.accounting.entitymodel;

import java.util.Date;

/**
 * PaymentMethodType generated by MyEclipse Persistence Tools
 */

public class PaymentMethodType extends com.magic.entitymodel.GenericEntity
		implements java.io.Serializable {

	// Fields

	private String paymentMethodTypeId;

	private String description;

	private String defaultGlAccountId;

	private Date lastUpdatedStamp;

	private Date lastUpdatedTxStamp;

	private Date createdStamp;

	private Date createdTxStamp;

	// Constructors

	/** default constructor */
	public PaymentMethodType() {
	}

	/** minimal constructor */
	public PaymentMethodType(String paymentMethodTypeId) {
		this.paymentMethodTypeId = paymentMethodTypeId;
	}

	/** full constructor */
	public PaymentMethodType(String paymentMethodTypeId, String description,
			String defaultGlAccountId, Date lastUpdatedStamp,
			Date lastUpdatedTxStamp, Date createdStamp, Date createdTxStamp) {
		this.paymentMethodTypeId = paymentMethodTypeId;
		this.description = description;
		this.defaultGlAccountId = defaultGlAccountId;
		this.lastUpdatedStamp = lastUpdatedStamp;
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
		this.createdStamp = createdStamp;
		this.createdTxStamp = createdTxStamp;
	}

	// Property accessors

	public String getPaymentMethodTypeId() {
		return this.paymentMethodTypeId;
	}

	public void setPaymentMethodTypeId(String paymentMethodTypeId) {
		this.paymentMethodTypeId = paymentMethodTypeId;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getDefaultGlAccountId() {
		return this.defaultGlAccountId;
	}

	public void setDefaultGlAccountId(String defaultGlAccountId) {
		this.defaultGlAccountId = defaultGlAccountId;
	}

	public Date getLastUpdatedStamp() {
		return this.lastUpdatedStamp;
	}

	public void setLastUpdatedStamp(Date lastUpdatedStamp) {
		this.lastUpdatedStamp = lastUpdatedStamp;
	}

	public Date getLastUpdatedTxStamp() {
		return this.lastUpdatedTxStamp;
	}

	public void setLastUpdatedTxStamp(Date lastUpdatedTxStamp) {
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
	}

	public Date getCreatedStamp() {
		return this.createdStamp;
	}

	public void setCreatedStamp(Date createdStamp) {
		this.createdStamp = createdStamp;
	}

	public Date getCreatedTxStamp() {
		return this.createdTxStamp;
	}

	public void setCreatedTxStamp(Date createdTxStamp) {
		this.createdTxStamp = createdTxStamp;
	}

}