package com.apps.accounting.entitymodel;

import java.util.Date;

/**
 * PaymentMethodTypeGlAccount generated by MyEclipse Persistence Tools
 */

public class PaymentMethodTypeGlAccount extends
		com.magic.entitymodel.GenericEntity implements java.io.Serializable {

	// Fields

	private PaymentMethodTypeGlAccountId id;

	private String glAccountId;

	private Date lastUpdatedStamp;

	private Date lastUpdatedTxStamp;

	private Date createdStamp;

	private Date createdTxStamp;

	// Constructors

	/** default constructor */
	public PaymentMethodTypeGlAccount() {
	}

	/** minimal constructor */
	public PaymentMethodTypeGlAccount(PaymentMethodTypeGlAccountId id) {
		this.id = id;
	}

	/** full constructor */
	public PaymentMethodTypeGlAccount(PaymentMethodTypeGlAccountId id,
			String glAccountId, Date lastUpdatedStamp, Date lastUpdatedTxStamp,
			Date createdStamp, Date createdTxStamp) {
		this.id = id;
		this.glAccountId = glAccountId;
		this.lastUpdatedStamp = lastUpdatedStamp;
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
		this.createdStamp = createdStamp;
		this.createdTxStamp = createdTxStamp;
	}

	// Property accessors

	public PaymentMethodTypeGlAccountId getId() {
		return this.id;
	}

	public void setId(PaymentMethodTypeGlAccountId id) {
		this.id = id;
	}

	public String getGlAccountId() {
		return this.glAccountId;
	}

	public void setGlAccountId(String glAccountId) {
		this.glAccountId = glAccountId;
	}

	public Date getLastUpdatedStamp() {
		return this.lastUpdatedStamp;
	}

	public void setLastUpdatedStamp(Date lastUpdatedStamp) {
		this.lastUpdatedStamp = lastUpdatedStamp;
	}

	public Date getLastUpdatedTxStamp() {
		return this.lastUpdatedTxStamp;
	}

	public void setLastUpdatedTxStamp(Date lastUpdatedTxStamp) {
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
	}

	public Date getCreatedStamp() {
		return this.createdStamp;
	}

	public void setCreatedStamp(Date createdStamp) {
		this.createdStamp = createdStamp;
	}

	public Date getCreatedTxStamp() {
		return this.createdTxStamp;
	}

	public void setCreatedTxStamp(Date createdTxStamp) {
		this.createdTxStamp = createdTxStamp;
	}

}