package com.apps.accounting.entitymodel;

import java.util.Date;

/**
 * PaymentGlAccountTypeMap generated by MyEclipse Persistence Tools
 */

public class PaymentGlAccountTypeMap extends
		com.magic.entitymodel.GenericEntity implements java.io.Serializable {

	// Fields

	private PaymentGlAccountTypeMapId id;

	private String glAccountTypeId;

	private Date lastUpdatedStamp;

	private Date lastUpdatedTxStamp;

	private Date createdStamp;

	private Date createdTxStamp;

	// Constructors

	/** default constructor */
	public PaymentGlAccountTypeMap() {
	}

	/** minimal constructor */
	public PaymentGlAccountTypeMap(PaymentGlAccountTypeMapId id) {
		this.id = id;
	}

	/** full constructor */
	public PaymentGlAccountTypeMap(PaymentGlAccountTypeMapId id,
			String glAccountTypeId, Date lastUpdatedStamp,
			Date lastUpdatedTxStamp, Date createdStamp, Date createdTxStamp) {
		this.id = id;
		this.glAccountTypeId = glAccountTypeId;
		this.lastUpdatedStamp = lastUpdatedStamp;
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
		this.createdStamp = createdStamp;
		this.createdTxStamp = createdTxStamp;
	}

	// Property accessors

	public PaymentGlAccountTypeMapId getId() {
		return this.id;
	}

	public void setId(PaymentGlAccountTypeMapId id) {
		this.id = id;
	}

	public String getGlAccountTypeId() {
		return this.glAccountTypeId;
	}

	public void setGlAccountTypeId(String glAccountTypeId) {
		this.glAccountTypeId = glAccountTypeId;
	}

	public Date getLastUpdatedStamp() {
		return this.lastUpdatedStamp;
	}

	public void setLastUpdatedStamp(Date lastUpdatedStamp) {
		this.lastUpdatedStamp = lastUpdatedStamp;
	}

	public Date getLastUpdatedTxStamp() {
		return this.lastUpdatedTxStamp;
	}

	public void setLastUpdatedTxStamp(Date lastUpdatedTxStamp) {
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
	}

	public Date getCreatedStamp() {
		return this.createdStamp;
	}

	public void setCreatedStamp(Date createdStamp) {
		this.createdStamp = createdStamp;
	}

	public Date getCreatedTxStamp() {
		return this.createdTxStamp;
	}

	public void setCreatedTxStamp(Date createdTxStamp) {
		this.createdTxStamp = createdTxStamp;
	}

}