package com.apps.product.entitymodel;

import java.util.Date;


/**
 * ProductType generated by MyEclipse Persistence Tools
 */

public class ProductType extends com.magic.entitymodel.GenericEntity implements java.io.Serializable {


    // Fields    

     private String productTypeId;
     private String parentTypeId;
     private String isPhysical;
     private String isDigital;
     private String hasTable;
     private String description;
     private Date lastUpdatedStamp;
     private Date lastUpdatedTxStamp;
     private Date createdStamp;
     private Date createdTxStamp;


    // Constructors

    /** default constructor */
    public ProductType() {
    }

	/** minimal constructor */
    public ProductType(String productTypeId) {
        this.productTypeId = productTypeId;
    }
    
    /** full constructor */
    public ProductType(String productTypeId, String parentTypeId, String isPhysical, String isDigital, String hasTable, String description, Date lastUpdatedStamp, Date lastUpdatedTxStamp, Date createdStamp, Date createdTxStamp) {
        this.productTypeId = productTypeId;
        this.parentTypeId = parentTypeId;
        this.isPhysical = isPhysical;
        this.isDigital = isDigital;
        this.hasTable = hasTable;
        this.description = description;
        this.lastUpdatedStamp = lastUpdatedStamp;
        this.lastUpdatedTxStamp = lastUpdatedTxStamp;
        this.createdStamp = createdStamp;
        this.createdTxStamp = createdTxStamp;
    }

   
    // Property accessors

    public String getProductTypeId() {
        return this.productTypeId;
    }
    
    public void setProductTypeId(String productTypeId) {
        this.productTypeId = productTypeId;
    }

    public String getParentTypeId() {
        return this.parentTypeId;
    }
    
    public void setParentTypeId(String parentTypeId) {
        this.parentTypeId = parentTypeId;
    }

    public String getIsPhysical() {
        return this.isPhysical;
    }
    
    public void setIsPhysical(String isPhysical) {
        this.isPhysical = isPhysical;
    }

    public String getIsDigital() {
        return this.isDigital;
    }
    
    public void setIsDigital(String isDigital) {
        this.isDigital = isDigital;
    }

    public String getHasTable() {
        return this.hasTable;
    }
    
    public void setHasTable(String hasTable) {
        this.hasTable = hasTable;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public Date getLastUpdatedStamp() {
        return this.lastUpdatedStamp;
    }
    
    public void setLastUpdatedStamp(Date lastUpdatedStamp) {
        this.lastUpdatedStamp = lastUpdatedStamp;
    }

    public Date getLastUpdatedTxStamp() {
        return this.lastUpdatedTxStamp;
    }
    
    public void setLastUpdatedTxStamp(Date lastUpdatedTxStamp) {
        this.lastUpdatedTxStamp = lastUpdatedTxStamp;
    }

    public Date getCreatedStamp() {
        return this.createdStamp;
    }
    
    public void setCreatedStamp(Date createdStamp) {
        this.createdStamp = createdStamp;
    }

    public Date getCreatedTxStamp() {
        return this.createdTxStamp;
    }
    
    public void setCreatedTxStamp(Date createdTxStamp) {
        this.createdTxStamp = createdTxStamp;
    }
   








}