package com.apps.product.entitymodel;

/**
 * ProductFacilityId generated by MyEclipse Persistence Tools
 */

public class ProductFacilityId extends com.magic.entitymodel.GenericEntity
		implements java.io.Serializable {

	// Fields

	private String productId;

	private String facilityId;

	// Constructors

	/** default constructor */
	public ProductFacilityId() {
	}

	/** full constructor */
	public ProductFacilityId(String productId, String facilityId) {
		this.productId = productId;
		this.facilityId = facilityId;
	}

	// Property accessors

	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	public String getFacilityId() {
		return this.facilityId;
	}

	public void setFacilityId(String facilityId) {
		this.facilityId = facilityId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProductFacilityId))
			return false;
		ProductFacilityId castOther = (ProductFacilityId) other;

		return ((this.getProductId() == castOther.getProductId()) || (this
				.getProductId() != null
				&& castOther.getProductId() != null && this.getProductId()
				.equals(castOther.getProductId())))
				&& ((this.getFacilityId() == castOther.getFacilityId()) || (this
						.getFacilityId() != null
						&& castOther.getFacilityId() != null && this
						.getFacilityId().equals(castOther.getFacilityId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getProductId() == null ? 0 : this.getProductId().hashCode());
		result = 37
				* result
				+ (getFacilityId() == null ? 0 : this.getFacilityId()
						.hashCode());
		return result;
	}

}