package com.apps.product.entitymodel;

import java.util.Date;

/**
 * ProductPriceId generated by MyEclipse Persistence Tools
 */

public class ProductPriceId
		implements java.io.Serializable {

	// Fields

	private String productId;

	private String productPriceTypeId;

	private String productPricePurposeId;

	private String currencyUomId;

	private String productStoreGroupId;

	private Date fromDate;

	// Constructors

	/** default constructor */
	public ProductPriceId() {
	}

	/** full constructor */
	public ProductPriceId(String productId, String productPriceTypeId,
			String productPricePurposeId, String currencyUomId,
			String productStoreGroupId, Date fromDate) {
		this.productId = productId;
		this.productPriceTypeId = productPriceTypeId;
		this.productPricePurposeId = productPricePurposeId;
		this.currencyUomId = currencyUomId;
		this.productStoreGroupId = productStoreGroupId;
		this.fromDate = fromDate;
	}

	// Property accessors

	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	public String getProductPriceTypeId() {
		return this.productPriceTypeId;
	}

	public void setProductPriceTypeId(String productPriceTypeId) {
		this.productPriceTypeId = productPriceTypeId;
	}

	public String getProductPricePurposeId() {
		return this.productPricePurposeId;
	}

	public void setProductPricePurposeId(String productPricePurposeId) {
		this.productPricePurposeId = productPricePurposeId;
	}

	public String getCurrencyUomId() {
		return this.currencyUomId;
	}

	public void setCurrencyUomId(String currencyUomId) {
		this.currencyUomId = currencyUomId;
	}

	public String getProductStoreGroupId() {
		return this.productStoreGroupId;
	}

	public void setProductStoreGroupId(String productStoreGroupId) {
		this.productStoreGroupId = productStoreGroupId;
	}

	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProductPriceId))
			return false;
		ProductPriceId castOther = (ProductPriceId) other;

		return ((this.getProductId() == castOther.getProductId()) || (this
				.getProductId() != null
				&& castOther.getProductId() != null && this.getProductId()
				.equals(castOther.getProductId())))
				&& ((this.getProductPriceTypeId() == castOther
						.getProductPriceTypeId()) || (this
						.getProductPriceTypeId() != null
						&& castOther.getProductPriceTypeId() != null && this
						.getProductPriceTypeId().equals(
								castOther.getProductPriceTypeId())))
				&& ((this.getProductPricePurposeId() == castOther
						.getProductPricePurposeId()) || (this
						.getProductPricePurposeId() != null
						&& castOther.getProductPricePurposeId() != null && this
						.getProductPricePurposeId().equals(
								castOther.getProductPricePurposeId())))
				&& ((this.getCurrencyUomId() == castOther.getCurrencyUomId()) || (this
						.getCurrencyUomId() != null
						&& castOther.getCurrencyUomId() != null && this
						.getCurrencyUomId()
						.equals(castOther.getCurrencyUomId())))
				&& ((this.getProductStoreGroupId() == castOther
						.getProductStoreGroupId()) || (this
						.getProductStoreGroupId() != null
						&& castOther.getProductStoreGroupId() != null && this
						.getProductStoreGroupId().equals(
								castOther.getProductStoreGroupId())))
				&& ((this.getFromDate() == castOther.getFromDate()) || (this
						.getFromDate() != null
						&& castOther.getFromDate() != null && this
						.getFromDate().equals(castOther.getFromDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getProductId() == null ? 0 : this.getProductId().hashCode());
		result = 37
				* result
				+ (getProductPriceTypeId() == null ? 0 : this
						.getProductPriceTypeId().hashCode());
		result = 37
				* result
				+ (getProductPricePurposeId() == null ? 0 : this
						.getProductPricePurposeId().hashCode());
		result = 37
				* result
				+ (getCurrencyUomId() == null ? 0 : this.getCurrencyUomId()
						.hashCode());
		result = 37
				* result
				+ (getProductStoreGroupId() == null ? 0 : this
						.getProductStoreGroupId().hashCode());
		result = 37 * result
				+ (getFromDate() == null ? 0 : this.getFromDate().hashCode());
		return result;
	}

}