package com.apps.product.entitymodel;

import java.util.Date;

/**
 * ProductFacility generated by MyEclipse Persistence Tools
 */

public class ProductFacility extends com.magic.entitymodel.GenericEntity
		implements java.io.Serializable {

	// Fields

	private ProductFacilityId id;

	private Double minimumStock;

	private Double reorderQuantity;

	private Long daysToShip;

	private Date lastUpdatedStamp;

	private Date lastUpdatedTxStamp;

	private Date createdStamp;

	private Date createdTxStamp;

	// Constructors

	/** default constructor */
	public ProductFacility() {
	}

	/** minimal constructor */
	public ProductFacility(ProductFacilityId id) {
		this.id = id;
	}

	/** full constructor */
	public ProductFacility(ProductFacilityId id, Double minimumStock,
			Double reorderQuantity, Long daysToShip, Date lastUpdatedStamp,
			Date lastUpdatedTxStamp, Date createdStamp, Date createdTxStamp) {
		this.id = id;
		this.minimumStock = minimumStock;
		this.reorderQuantity = reorderQuantity;
		this.daysToShip = daysToShip;
		this.lastUpdatedStamp = lastUpdatedStamp;
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
		this.createdStamp = createdStamp;
		this.createdTxStamp = createdTxStamp;
	}

	// Property accessors

	public ProductFacilityId getId() {
		return this.id;
	}

	public void setId(ProductFacilityId id) {
		this.id = id;
	}

	public Double getMinimumStock() {
		return this.minimumStock;
	}

	public void setMinimumStock(Double minimumStock) {
		this.minimumStock = minimumStock;
	}

	public Double getReorderQuantity() {
		return this.reorderQuantity;
	}

	public void setReorderQuantity(Double reorderQuantity) {
		this.reorderQuantity = reorderQuantity;
	}

	public Long getDaysToShip() {
		return this.daysToShip;
	}

	public void setDaysToShip(Long daysToShip) {
		this.daysToShip = daysToShip;
	}

	public Date getLastUpdatedStamp() {
		return this.lastUpdatedStamp;
	}

	public void setLastUpdatedStamp(Date lastUpdatedStamp) {
		this.lastUpdatedStamp = lastUpdatedStamp;
	}

	public Date getLastUpdatedTxStamp() {
		return this.lastUpdatedTxStamp;
	}

	public void setLastUpdatedTxStamp(Date lastUpdatedTxStamp) {
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
	}

	public Date getCreatedStamp() {
		return this.createdStamp;
	}

	public void setCreatedStamp(Date createdStamp) {
		this.createdStamp = createdStamp;
	}

	public Date getCreatedTxStamp() {
		return this.createdTxStamp;
	}

	public void setCreatedTxStamp(Date createdTxStamp) {
		this.createdTxStamp = createdTxStamp;
	}

}