package com.apps.product.entitymodel;

/**
 * ProductAttributeId generated by MyEclipse Persistence Tools
 */

public class ProductAttributeId implements java.io.Serializable {

	// Fields

	private String productId;

	private String attrName;

	// Constructors

	/** default constructor */
	public ProductAttributeId() {
	}

	/** full constructor */
	public ProductAttributeId(String productId, String attrName) {
		this.productId = productId;
		this.attrName = attrName;
	}

	// Property accessors

	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	public String getAttrName() {
		return this.attrName;
	}

	public void setAttrName(String attrName) {
		this.attrName = attrName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProductAttributeId))
			return false;
		ProductAttributeId castOther = (ProductAttributeId) other;

		return ((this.getProductId() == castOther.getProductId()) || (this
				.getProductId() != null
				&& castOther.getProductId() != null && this.getProductId()
				.equals(castOther.getProductId())))
				&& ((this.getAttrName() == castOther.getAttrName()) || (this
						.getAttrName() != null
						&& castOther.getAttrName() != null && this
						.getAttrName().equals(castOther.getAttrName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getProductId() == null ? 0 : this.getProductId().hashCode());
		result = 37 * result
				+ (getAttrName() == null ? 0 : this.getAttrName().hashCode());
		return result;
	}

}