package com.frm.content.entitymodel;

import java.util.Date;

/**
 * WebSiteContentId generated by MyEclipse Persistence Tools
 */

public class WebSiteContentId extends com.magic.entitymodel.GenericEntity
		implements java.io.Serializable {

	// Fields

	private String webSiteId;

	private String contentId;

	private String webSiteContentTypeId;

	private Date fromDate;

	// Constructors

	/** default constructor */
	public WebSiteContentId() {
	}

	/** full constructor */
	public WebSiteContentId(String webSiteId, String contentId,
			String webSiteContentTypeId, Date fromDate) {
		this.webSiteId = webSiteId;
		this.contentId = contentId;
		this.webSiteContentTypeId = webSiteContentTypeId;
		this.fromDate = fromDate;
	}

	// Property accessors

	public String getWebSiteId() {
		return this.webSiteId;
	}

	public void setWebSiteId(String webSiteId) {
		this.webSiteId = webSiteId;
	}

	public String getContentId() {
		return this.contentId;
	}

	public void setContentId(String contentId) {
		this.contentId = contentId;
	}

	public String getWebSiteContentTypeId() {
		return this.webSiteContentTypeId;
	}

	public void setWebSiteContentTypeId(String webSiteContentTypeId) {
		this.webSiteContentTypeId = webSiteContentTypeId;
	}

	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof WebSiteContentId))
			return false;
		WebSiteContentId castOther = (WebSiteContentId) other;

		return ((this.getWebSiteId() == castOther.getWebSiteId()) || (this
				.getWebSiteId() != null
				&& castOther.getWebSiteId() != null && this.getWebSiteId()
				.equals(castOther.getWebSiteId())))
				&& ((this.getContentId() == castOther.getContentId()) || (this
						.getContentId() != null
						&& castOther.getContentId() != null && this
						.getContentId().equals(castOther.getContentId())))
				&& ((this.getWebSiteContentTypeId() == castOther
						.getWebSiteContentTypeId()) || (this
						.getWebSiteContentTypeId() != null
						&& castOther.getWebSiteContentTypeId() != null && this
						.getWebSiteContentTypeId().equals(
								castOther.getWebSiteContentTypeId())))
				&& ((this.getFromDate() == castOther.getFromDate()) || (this
						.getFromDate() != null
						&& castOther.getFromDate() != null && this
						.getFromDate().equals(castOther.getFromDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getWebSiteId() == null ? 0 : this.getWebSiteId().hashCode());
		result = 37 * result
				+ (getContentId() == null ? 0 : this.getContentId().hashCode());
		result = 37
				* result
				+ (getWebSiteContentTypeId() == null ? 0 : this
						.getWebSiteContentTypeId().hashCode());
		result = 37 * result
				+ (getFromDate() == null ? 0 : this.getFromDate().hashCode());
		return result;
	}

}