package com.frm.content.entitymodel;

import java.util.Date;

/**
 * WebSiteContentType generated by MyEclipse Persistence Tools
 */

public class WebSiteContentType extends com.magic.entitymodel.GenericEntity
		implements java.io.Serializable {

	// Fields

	private String webSiteContentTypeId;

	private String description;

	private String parentTypeId;

	private String hasTable;

	private Date lastUpdatedStamp;

	private Date lastUpdatedTxStamp;

	private Date createdStamp;

	private Date createdTxStamp;

	// Constructors

	/** default constructor */
	public WebSiteContentType() {
	}

	/** minimal constructor */
	public WebSiteContentType(String webSiteContentTypeId) {
		this.webSiteContentTypeId = webSiteContentTypeId;
	}

	/** full constructor */
	public WebSiteContentType(String webSiteContentTypeId, String description,
			String parentTypeId, String hasTable, Date lastUpdatedStamp,
			Date lastUpdatedTxStamp, Date createdStamp, Date createdTxStamp) {
		this.webSiteContentTypeId = webSiteContentTypeId;
		this.description = description;
		this.parentTypeId = parentTypeId;
		this.hasTable = hasTable;
		this.lastUpdatedStamp = lastUpdatedStamp;
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
		this.createdStamp = createdStamp;
		this.createdTxStamp = createdTxStamp;
	}

	// Property accessors

	public String getWebSiteContentTypeId() {
		return this.webSiteContentTypeId;
	}

	public void setWebSiteContentTypeId(String webSiteContentTypeId) {
		this.webSiteContentTypeId = webSiteContentTypeId;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getParentTypeId() {
		return this.parentTypeId;
	}

	public void setParentTypeId(String parentTypeId) {
		this.parentTypeId = parentTypeId;
	}

	public String getHasTable() {
		return this.hasTable;
	}

	public void setHasTable(String hasTable) {
		this.hasTable = hasTable;
	}

	public Date getLastUpdatedStamp() {
		return this.lastUpdatedStamp;
	}

	public void setLastUpdatedStamp(Date lastUpdatedStamp) {
		this.lastUpdatedStamp = lastUpdatedStamp;
	}

	public Date getLastUpdatedTxStamp() {
		return this.lastUpdatedTxStamp;
	}

	public void setLastUpdatedTxStamp(Date lastUpdatedTxStamp) {
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
	}

	public Date getCreatedStamp() {
		return this.createdStamp;
	}

	public void setCreatedStamp(Date createdStamp) {
		this.createdStamp = createdStamp;
	}

	public Date getCreatedTxStamp() {
		return this.createdTxStamp;
	}

	public void setCreatedTxStamp(Date createdTxStamp) {
		this.createdTxStamp = createdTxStamp;
	}

}