package com.apps.party.entitymodel;

/**
 * PartyAttributeId generated by MyEclipse Persistence Tools
 */

public class PartyAttributeId implements java.io.Serializable {

	// Fields

	private String partyId;

	private String attrName;

	// Constructors

	/** default constructor */
	public PartyAttributeId() {
	}

	/** full constructor */
	public PartyAttributeId(String partyId, String attrName) {
		this.partyId = partyId;
		this.attrName = attrName;
	}

	// Property accessors

	public String getPartyId() {
		return this.partyId;
	}

	public void setPartyId(String partyId) {
		this.partyId = partyId;
	}

	public String getAttrName() {
		return this.attrName;
	}

	public void setAttrName(String attrName) {
		this.attrName = attrName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PartyAttributeId))
			return false;
		PartyAttributeId castOther = (PartyAttributeId) other;

		return ((this.getPartyId() == castOther.getPartyId()) || (this
				.getPartyId() != null
				&& castOther.getPartyId() != null && this.getPartyId().equals(
				castOther.getPartyId())))
				&& ((this.getAttrName() == castOther.getAttrName()) || (this
						.getAttrName() != null
						&& castOther.getAttrName() != null && this
						.getAttrName().equals(castOther.getAttrName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getPartyId() == null ? 0 : this.getPartyId().hashCode());
		result = 37 * result
				+ (getAttrName() == null ? 0 : this.getAttrName().hashCode());
		return result;
	}

}