package com.apps.party.entitymodel;

import java.util.Date;

import org.springframework.stereotype.Service;

import com.magic.entitymodel.GenericEntity;

/**
 * Party generated by MyEclipse Persistence Tools
 */
public class Party extends GenericEntity implements java.io.Serializable {

	// Fields

	private String partyId;

	private String partyTypeId;

	private String externalId;

	private String preferredCurrencyUomId;

	private String description;

	private String statusId;

	private Date createdDate;

	private String createdByUserLogin;

	private Date lastModifiedDate;

	private String lastModifiedByUserLogin;

	private String dataSourceId;

	private String isUnread;

	private Date lastUpdatedStamp;

	private Date lastUpdatedTxStamp;

	private Date createdStamp;

	private Date createdTxStamp;

	// Constructors

	/** default constructor */
	public Party() {
	}

	/** minimal constructor */
	public Party(String partyId) {
		this.partyId = partyId;
	}

	/** full constructor */
	public Party(String partyId, String partyTypeId, String externalId,
			String preferredCurrencyUomId, String description, String statusId,
			Date createdDate, String createdByUserLogin, Date lastModifiedDate,
			String lastModifiedByUserLogin, String dataSourceId,
			String isUnread, Date lastUpdatedStamp, Date lastUpdatedTxStamp,
			Date createdStamp, Date createdTxStamp) {
		this.partyId = partyId;
		this.partyTypeId = partyTypeId;
		this.externalId = externalId;
		this.preferredCurrencyUomId = preferredCurrencyUomId;
		this.description = description;
		this.statusId = statusId;
		this.createdDate = createdDate;
		this.createdByUserLogin = createdByUserLogin;
		this.lastModifiedDate = lastModifiedDate;
		this.lastModifiedByUserLogin = lastModifiedByUserLogin;
		this.dataSourceId = dataSourceId;
		this.isUnread = isUnread;
		this.lastUpdatedStamp = lastUpdatedStamp;
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
		this.createdStamp = createdStamp;
		this.createdTxStamp = createdTxStamp;
	}

	// Property accessors

	public String getPartyId() {
		return this.partyId;
	}

	public void setPartyId(String partyId) {
		this.partyId = partyId;
	}

	public String getPartyTypeId() {
		return this.partyTypeId;
	}

	public void setPartyTypeId(String partyTypeId) {
		this.partyTypeId = partyTypeId;
	}

	public String getExternalId() {
		return this.externalId;
	}

	public void setExternalId(String externalId) {
		this.externalId = externalId;
	}

	public String getPreferredCurrencyUomId() {
		return this.preferredCurrencyUomId;
	}

	public void setPreferredCurrencyUomId(String preferredCurrencyUomId) {
		this.preferredCurrencyUomId = preferredCurrencyUomId;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getStatusId() {
		return this.statusId;
	}

	public void setStatusId(String statusId) {
		this.statusId = statusId;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getCreatedByUserLogin() {
		return this.createdByUserLogin;
	}

	public void setCreatedByUserLogin(String createdByUserLogin) {
		this.createdByUserLogin = createdByUserLogin;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public String getLastModifiedByUserLogin() {
		return this.lastModifiedByUserLogin;
	}

	public void setLastModifiedByUserLogin(String lastModifiedByUserLogin) {
		this.lastModifiedByUserLogin = lastModifiedByUserLogin;
	}

	public String getDataSourceId() {
		return this.dataSourceId;
	}

	public void setDataSourceId(String dataSourceId) {
		this.dataSourceId = dataSourceId;
	}

	public String getIsUnread() {
		return this.isUnread;
	}

	public void setIsUnread(String isUnread) {
		this.isUnread = isUnread;
	}

	public Date getLastUpdatedStamp() {
		return this.lastUpdatedStamp;
	}

	public void setLastUpdatedStamp(Date lastUpdatedStamp) {
		this.lastUpdatedStamp = lastUpdatedStamp;
	}

	public Date getLastUpdatedTxStamp() {
		return this.lastUpdatedTxStamp;
	}

	public void setLastUpdatedTxStamp(Date lastUpdatedTxStamp) {
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
	}

	public Date getCreatedStamp() {
		return this.createdStamp;
	}

	public void setCreatedStamp(Date createdStamp) {
		this.createdStamp = createdStamp;
	}

	public Date getCreatedTxStamp() {
		return this.createdTxStamp;
	}

	public void setCreatedTxStamp(Date createdTxStamp) {
		this.createdTxStamp = createdTxStamp;
	}

}