package com.apps.party.entitymodel;

import java.util.Date;

/**
 * PartyRelationshipId generated by MyEclipse Persistence Tools
 */

public class PartyRelationshipId
		implements java.io.Serializable {

	// Fields

	private String partyIdFrom;

	private String partyIdTo;

	private String roleTypeIdFrom;

	private String roleTypeIdTo;

	private Date fromDate;

	// Constructors

	/** default constructor */
	public PartyRelationshipId() {
	}

	/** full constructor */
	public PartyRelationshipId(String partyIdFrom, String partyIdTo,
			String roleTypeIdFrom, String roleTypeIdTo, Date fromDate) {
		this.partyIdFrom = partyIdFrom;
		this.partyIdTo = partyIdTo;
		this.roleTypeIdFrom = roleTypeIdFrom;
		this.roleTypeIdTo = roleTypeIdTo;
		this.fromDate = fromDate;
	}

	// Property accessors

	public String getPartyIdFrom() {
		return this.partyIdFrom;
	}

	public void setPartyIdFrom(String partyIdFrom) {
		this.partyIdFrom = partyIdFrom;
	}

	public String getPartyIdTo() {
		return this.partyIdTo;
	}

	public void setPartyIdTo(String partyIdTo) {
		this.partyIdTo = partyIdTo;
	}

	public String getRoleTypeIdFrom() {
		return this.roleTypeIdFrom;
	}

	public void setRoleTypeIdFrom(String roleTypeIdFrom) {
		this.roleTypeIdFrom = roleTypeIdFrom;
	}

	public String getRoleTypeIdTo() {
		return this.roleTypeIdTo;
	}

	public void setRoleTypeIdTo(String roleTypeIdTo) {
		this.roleTypeIdTo = roleTypeIdTo;
	}

	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PartyRelationshipId))
			return false;
		PartyRelationshipId castOther = (PartyRelationshipId) other;

		return ((this.getPartyIdFrom() == castOther.getPartyIdFrom()) || (this
				.getPartyIdFrom() != null
				&& castOther.getPartyIdFrom() != null && this.getPartyIdFrom()
				.equals(castOther.getPartyIdFrom())))
				&& ((this.getPartyIdTo() == castOther.getPartyIdTo()) || (this
						.getPartyIdTo() != null
						&& castOther.getPartyIdTo() != null && this
						.getPartyIdTo().equals(castOther.getPartyIdTo())))
				&& ((this.getRoleTypeIdFrom() == castOther.getRoleTypeIdFrom()) || (this
						.getRoleTypeIdFrom() != null
						&& castOther.getRoleTypeIdFrom() != null && this
						.getRoleTypeIdFrom().equals(
								castOther.getRoleTypeIdFrom())))
				&& ((this.getRoleTypeIdTo() == castOther.getRoleTypeIdTo()) || (this
						.getRoleTypeIdTo() != null
						&& castOther.getRoleTypeIdTo() != null && this
						.getRoleTypeIdTo().equals(castOther.getRoleTypeIdTo())))
				&& ((this.getFromDate() == castOther.getFromDate()) || (this
						.getFromDate() != null
						&& castOther.getFromDate() != null && this
						.getFromDate().equals(castOther.getFromDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getPartyIdFrom() == null ? 0 : this.getPartyIdFrom()
						.hashCode());
		result = 37 * result
				+ (getPartyIdTo() == null ? 0 : this.getPartyIdTo().hashCode());
		result = 37
				* result
				+ (getRoleTypeIdFrom() == null ? 0 : this.getRoleTypeIdFrom()
						.hashCode());
		result = 37
				* result
				+ (getRoleTypeIdTo() == null ? 0 : this.getRoleTypeIdTo()
						.hashCode());
		result = 37 * result
				+ (getFromDate() == null ? 0 : this.getFromDate().hashCode());
		return result;
	}

}