package com.apps.party.entitymodel;

import java.util.Date;

import org.springframework.stereotype.Service;

/**
 * PartyGroup generated by MyEclipse Persistence Tools
 */

public class PartyGroup extends com.magic.entitymodel.GenericEntity implements
		java.io.Serializable {

	// Fields

	private String partyId;

	private String groupName;

	private String groupNameLocal;

	private String officeSiteName;

	private Double annualRevenue;

	private Long numEmployees;

	private String tickerSymbol;

	private String comments;

	private String logoImageUrl;

	private Date lastUpdatedStamp;

	private Date lastUpdatedTxStamp;

	private Date createdStamp;

	private Date createdTxStamp;

	// Constructors

	/** default constructor */
	public PartyGroup() {
	}

	/** minimal constructor */
	public PartyGroup(String partyId) {
		this.partyId = partyId;
	}

	/** full constructor */
	public PartyGroup(String partyId, String groupName, String groupNameLocal,
			String officeSiteName, Double annualRevenue, Long numEmployees,
			String tickerSymbol, String comments, String logoImageUrl,
			Date lastUpdatedStamp, Date lastUpdatedTxStamp, Date createdStamp,
			Date createdTxStamp) {
		this.partyId = partyId;
		this.groupName = groupName;
		this.groupNameLocal = groupNameLocal;
		this.officeSiteName = officeSiteName;
		this.annualRevenue = annualRevenue;
		this.numEmployees = numEmployees;
		this.tickerSymbol = tickerSymbol;
		this.comments = comments;
		this.logoImageUrl = logoImageUrl;
		this.lastUpdatedStamp = lastUpdatedStamp;
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
		this.createdStamp = createdStamp;
		this.createdTxStamp = createdTxStamp;
	}

	// Property accessors

	public String getPartyId() {
		return this.partyId;
	}

	public void setPartyId(String partyId) {
		this.partyId = partyId;
	}

	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	public String getGroupNameLocal() {
		return this.groupNameLocal;
	}

	public void setGroupNameLocal(String groupNameLocal) {
		this.groupNameLocal = groupNameLocal;
	}

	public String getOfficeSiteName() {
		return this.officeSiteName;
	}

	public void setOfficeSiteName(String officeSiteName) {
		this.officeSiteName = officeSiteName;
	}

	public Double getAnnualRevenue() {
		return this.annualRevenue;
	}

	public void setAnnualRevenue(Double annualRevenue) {
		this.annualRevenue = annualRevenue;
	}

	public Long getNumEmployees() {
		return this.numEmployees;
	}

	public void setNumEmployees(Long numEmployees) {
		this.numEmployees = numEmployees;
	}

	public String getTickerSymbol() {
		return this.tickerSymbol;
	}

	public void setTickerSymbol(String tickerSymbol) {
		this.tickerSymbol = tickerSymbol;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public String getLogoImageUrl() {
		return this.logoImageUrl;
	}

	public void setLogoImageUrl(String logoImageUrl) {
		this.logoImageUrl = logoImageUrl;
	}

	public Date getLastUpdatedStamp() {
		return this.lastUpdatedStamp;
	}

	public void setLastUpdatedStamp(Date lastUpdatedStamp) {
		this.lastUpdatedStamp = lastUpdatedStamp;
	}

	public Date getLastUpdatedTxStamp() {
		return this.lastUpdatedTxStamp;
	}

	public void setLastUpdatedTxStamp(Date lastUpdatedTxStamp) {
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
	}

	public Date getCreatedStamp() {
		return this.createdStamp;
	}

	public void setCreatedStamp(Date createdStamp) {
		this.createdStamp = createdStamp;
	}

	public Date getCreatedTxStamp() {
		return this.createdTxStamp;
	}

	public void setCreatedTxStamp(Date createdTxStamp) {
		this.createdTxStamp = createdTxStamp;
	}

}