package com.apps.party.entitymodel;

import java.util.Date;

/**
 * PartyRelationship generated by MyEclipse Persistence Tools
 */

public class PartyRelationship extends com.magic.entitymodel.GenericEntity
		implements java.io.Serializable {

	// Fields

	private PartyRelationshipId id;

	private Date thruDate;

	private String statusId;

	private String relationshipName;

	private String securityGroupId;

	private String priorityTypeId;

	private String partyRelationshipTypeId;

	private String permissionsEnumId;

	private String positionTitle;

	private String comments;

	private Date lastUpdatedStamp;

	private Date lastUpdatedTxStamp;

	private Date createdStamp;

	private Date createdTxStamp;

	// Constructors

	/** default constructor */
	public PartyRelationship() {
	}

	/** minimal constructor */
	public PartyRelationship(PartyRelationshipId id) {
		this.id = id;
	}

	/** full constructor */
	public PartyRelationship(PartyRelationshipId id, Date thruDate,
			String statusId, String relationshipName, String securityGroupId,
			String priorityTypeId, String partyRelationshipTypeId,
			String permissionsEnumId, String positionTitle, String comments,
			Date lastUpdatedStamp, Date lastUpdatedTxStamp, Date createdStamp,
			Date createdTxStamp) {
		this.id = id;
		this.thruDate = thruDate;
		this.statusId = statusId;
		this.relationshipName = relationshipName;
		this.securityGroupId = securityGroupId;
		this.priorityTypeId = priorityTypeId;
		this.partyRelationshipTypeId = partyRelationshipTypeId;
		this.permissionsEnumId = permissionsEnumId;
		this.positionTitle = positionTitle;
		this.comments = comments;
		this.lastUpdatedStamp = lastUpdatedStamp;
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
		this.createdStamp = createdStamp;
		this.createdTxStamp = createdTxStamp;
	}

	// Property accessors

	public PartyRelationshipId getId() {
		return this.id;
	}

	public void setId(PartyRelationshipId id) {
		this.id = id;
	}

	public Date getThruDate() {
		return this.thruDate;
	}

	public void setThruDate(Date thruDate) {
		this.thruDate = thruDate;
	}

	public String getStatusId() {
		return this.statusId;
	}

	public void setStatusId(String statusId) {
		this.statusId = statusId;
	}

	public String getRelationshipName() {
		return this.relationshipName;
	}

	public void setRelationshipName(String relationshipName) {
		this.relationshipName = relationshipName;
	}

	public String getSecurityGroupId() {
		return this.securityGroupId;
	}

	public void setSecurityGroupId(String securityGroupId) {
		this.securityGroupId = securityGroupId;
	}

	public String getPriorityTypeId() {
		return this.priorityTypeId;
	}

	public void setPriorityTypeId(String priorityTypeId) {
		this.priorityTypeId = priorityTypeId;
	}

	public String getPartyRelationshipTypeId() {
		return this.partyRelationshipTypeId;
	}

	public void setPartyRelationshipTypeId(String partyRelationshipTypeId) {
		this.partyRelationshipTypeId = partyRelationshipTypeId;
	}

	public String getPermissionsEnumId() {
		return this.permissionsEnumId;
	}

	public void setPermissionsEnumId(String permissionsEnumId) {
		this.permissionsEnumId = permissionsEnumId;
	}

	public String getPositionTitle() {
		return this.positionTitle;
	}

	public void setPositionTitle(String positionTitle) {
		this.positionTitle = positionTitle;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public Date getLastUpdatedStamp() {
		return this.lastUpdatedStamp;
	}

	public void setLastUpdatedStamp(Date lastUpdatedStamp) {
		this.lastUpdatedStamp = lastUpdatedStamp;
	}

	public Date getLastUpdatedTxStamp() {
		return this.lastUpdatedTxStamp;
	}

	public void setLastUpdatedTxStamp(Date lastUpdatedTxStamp) {
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
	}

	public Date getCreatedStamp() {
		return this.createdStamp;
	}

	public void setCreatedStamp(Date createdStamp) {
		this.createdStamp = createdStamp;
	}

	public Date getCreatedTxStamp() {
		return this.createdTxStamp;
	}

	public void setCreatedTxStamp(Date createdTxStamp) {
		this.createdTxStamp = createdTxStamp;
	}

}