package com.apps.party.entitymodel;

import java.util.Date;

/**
 * PartyContactMechId generated by MyEclipse Persistence Tools
 */

public class PartyContactMechId extends com.magic.entitymodel.GenericEntity
		implements java.io.Serializable {

	// Fields

	private String partyId;

	private String contactMechId;

	private Date fromDate;

	// Constructors

	/** default constructor */
	public PartyContactMechId() {
	}

	/** full constructor */
	public PartyContactMechId(String partyId, String contactMechId,
			Date fromDate) {
		this.partyId = partyId;
		this.contactMechId = contactMechId;
		this.fromDate = fromDate;
	}

	// Property accessors

	public String getPartyId() {
		return this.partyId;
	}

	public void setPartyId(String partyId) {
		this.partyId = partyId;
	}

	public String getContactMechId() {
		return this.contactMechId;
	}

	public void setContactMechId(String contactMechId) {
		this.contactMechId = contactMechId;
	}

	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PartyContactMechId))
			return false;
		PartyContactMechId castOther = (PartyContactMechId) other;

		return ((this.getPartyId() == castOther.getPartyId()) || (this
				.getPartyId() != null
				&& castOther.getPartyId() != null && this.getPartyId().equals(
				castOther.getPartyId())))
				&& ((this.getContactMechId() == castOther.getContactMechId()) || (this
						.getContactMechId() != null
						&& castOther.getContactMechId() != null && this
						.getContactMechId()
						.equals(castOther.getContactMechId())))
				&& ((this.getFromDate() == castOther.getFromDate()) || (this
						.getFromDate() != null
						&& castOther.getFromDate() != null && this
						.getFromDate().equals(castOther.getFromDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getPartyId() == null ? 0 : this.getPartyId().hashCode());
		result = 37
				* result
				+ (getContactMechId() == null ? 0 : this.getContactMechId()
						.hashCode());
		result = 37 * result
				+ (getFromDate() == null ? 0 : this.getFromDate().hashCode());
		return result;
	}

}