package com.apps.party.entitymodel;

import java.util.Date;

/**
 * PartyRelationshipType generated by MyEclipse Persistence Tools
 */

public class PartyRelationshipType extends com.magic.entitymodel.GenericEntity
		implements java.io.Serializable {

	// Fields

	private String partyRelationshipTypeId;

	private String parentTypeId;

	private String hasTable;

	private String partyRelationshipName;

	private String description;

	private String roleTypeIdValidFrom;

	private String roleTypeIdValidTo;

	private Date lastUpdatedStamp;

	private Date lastUpdatedTxStamp;

	private Date createdStamp;

	private Date createdTxStamp;

	// Constructors

	/** default constructor */
	public PartyRelationshipType() {
	}

	/** minimal constructor */
	public PartyRelationshipType(String partyRelationshipTypeId) {
		this.partyRelationshipTypeId = partyRelationshipTypeId;
	}

	/** full constructor */
	public PartyRelationshipType(String partyRelationshipTypeId,
			String parentTypeId, String hasTable, String partyRelationshipName,
			String description, String roleTypeIdValidFrom,
			String roleTypeIdValidTo, Date lastUpdatedStamp,
			Date lastUpdatedTxStamp, Date createdStamp, Date createdTxStamp) {
		this.partyRelationshipTypeId = partyRelationshipTypeId;
		this.parentTypeId = parentTypeId;
		this.hasTable = hasTable;
		this.partyRelationshipName = partyRelationshipName;
		this.description = description;
		this.roleTypeIdValidFrom = roleTypeIdValidFrom;
		this.roleTypeIdValidTo = roleTypeIdValidTo;
		this.lastUpdatedStamp = lastUpdatedStamp;
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
		this.createdStamp = createdStamp;
		this.createdTxStamp = createdTxStamp;
	}

	// Property accessors

	public String getPartyRelationshipTypeId() {
		return this.partyRelationshipTypeId;
	}

	public void setPartyRelationshipTypeId(String partyRelationshipTypeId) {
		this.partyRelationshipTypeId = partyRelationshipTypeId;
	}

	public String getParentTypeId() {
		return this.parentTypeId;
	}

	public void setParentTypeId(String parentTypeId) {
		this.parentTypeId = parentTypeId;
	}

	public String getHasTable() {
		return this.hasTable;
	}

	public void setHasTable(String hasTable) {
		this.hasTable = hasTable;
	}

	public String getPartyRelationshipName() {
		return this.partyRelationshipName;
	}

	public void setPartyRelationshipName(String partyRelationshipName) {
		this.partyRelationshipName = partyRelationshipName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getRoleTypeIdValidFrom() {
		return this.roleTypeIdValidFrom;
	}

	public void setRoleTypeIdValidFrom(String roleTypeIdValidFrom) {
		this.roleTypeIdValidFrom = roleTypeIdValidFrom;
	}

	public String getRoleTypeIdValidTo() {
		return this.roleTypeIdValidTo;
	}

	public void setRoleTypeIdValidTo(String roleTypeIdValidTo) {
		this.roleTypeIdValidTo = roleTypeIdValidTo;
	}

	public Date getLastUpdatedStamp() {
		return this.lastUpdatedStamp;
	}

	public void setLastUpdatedStamp(Date lastUpdatedStamp) {
		this.lastUpdatedStamp = lastUpdatedStamp;
	}

	public Date getLastUpdatedTxStamp() {
		return this.lastUpdatedTxStamp;
	}

	public void setLastUpdatedTxStamp(Date lastUpdatedTxStamp) {
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
	}

	public Date getCreatedStamp() {
		return this.createdStamp;
	}

	public void setCreatedStamp(Date createdStamp) {
		this.createdStamp = createdStamp;
	}

	public Date getCreatedTxStamp() {
		return this.createdTxStamp;
	}

	public void setCreatedTxStamp(Date createdTxStamp) {
		this.createdTxStamp = createdTxStamp;
	}

}