package com.apps.party.entitymodel;

/**
 * PartyRoleId generated by MyEclipse Persistence Tools
 */

public class PartyRoleId extends com.magic.entitymodel.GenericEntity implements
		java.io.Serializable {

	// Fields

	private String partyId;

	private String roleTypeId;

	// Constructors

	/** default constructor */
	public PartyRoleId() {
	}

	/** full constructor */
	public PartyRoleId(String partyId, String roleTypeId) {
		this.partyId = partyId;
		this.roleTypeId = roleTypeId;
	}

	// Property accessors

	public String getPartyId() {
		return this.partyId;
	}

	public void setPartyId(String partyId) {
		this.partyId = partyId;
	}

	public String getRoleTypeId() {
		return this.roleTypeId;
	}

	public void setRoleTypeId(String roleTypeId) {
		this.roleTypeId = roleTypeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PartyRoleId))
			return false;
		PartyRoleId castOther = (PartyRoleId) other;

		return ((this.getPartyId() == castOther.getPartyId()) || (this
				.getPartyId() != null
				&& castOther.getPartyId() != null && this.getPartyId().equals(
				castOther.getPartyId())))
				&& ((this.getRoleTypeId() == castOther.getRoleTypeId()) || (this
						.getRoleTypeId() != null
						&& castOther.getRoleTypeId() != null && this
						.getRoleTypeId().equals(castOther.getRoleTypeId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getPartyId() == null ? 0 : this.getPartyId().hashCode());
		result = 37
				* result
				+ (getRoleTypeId() == null ? 0 : this.getRoleTypeId()
						.hashCode());
		return result;
	}

}