package com.apps.party.entitymodel;

import java.util.Date;

/**
 * PartyContactMech generated by MyEclipse Persistence Tools
 */

public class PartyContactMech extends com.magic.entitymodel.GenericEntity
		implements java.io.Serializable {

	// Fields

	private PartyContactMechId id;

	private Date thruDate;

	private String roleTypeId;

	private String allowSolicitation;

	private String extension;

	private String verified;

	private String comments;

	private Long yearsWithContactMech;

	private Long monthsWithContactMech;

	private Date lastUpdatedStamp;

	private Date lastUpdatedTxStamp;

	private Date createdStamp;

	private Date createdTxStamp;

	// Constructors

	/** default constructor */
	public PartyContactMech() {
	}

	/** minimal constructor */
	public PartyContactMech(PartyContactMechId id) {
		this.id = id;
	}

	/** full constructor */
	public PartyContactMech(PartyContactMechId id, Date thruDate,
			String roleTypeId, String allowSolicitation, String extension,
			String verified, String comments, Long yearsWithContactMech,
			Long monthsWithContactMech, Date lastUpdatedStamp,
			Date lastUpdatedTxStamp, Date createdStamp, Date createdTxStamp) {
		this.id = id;
		this.thruDate = thruDate;
		this.roleTypeId = roleTypeId;
		this.allowSolicitation = allowSolicitation;
		this.extension = extension;
		this.verified = verified;
		this.comments = comments;
		this.yearsWithContactMech = yearsWithContactMech;
		this.monthsWithContactMech = monthsWithContactMech;
		this.lastUpdatedStamp = lastUpdatedStamp;
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
		this.createdStamp = createdStamp;
		this.createdTxStamp = createdTxStamp;
	}

	// Property accessors

	public PartyContactMechId getId() {
		return this.id;
	}

	public void setId(PartyContactMechId id) {
		this.id = id;
	}

	public Date getThruDate() {
		return this.thruDate;
	}

	public void setThruDate(Date thruDate) {
		this.thruDate = thruDate;
	}

	public String getRoleTypeId() {
		return this.roleTypeId;
	}

	public void setRoleTypeId(String roleTypeId) {
		this.roleTypeId = roleTypeId;
	}

	public String getAllowSolicitation() {
		return this.allowSolicitation;
	}

	public void setAllowSolicitation(String allowSolicitation) {
		this.allowSolicitation = allowSolicitation;
	}

	public String getExtension() {
		return this.extension;
	}

	public void setExtension(String extension) {
		this.extension = extension;
	}

	public String getVerified() {
		return this.verified;
	}

	public void setVerified(String verified) {
		this.verified = verified;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public Long getYearsWithContactMech() {
		return this.yearsWithContactMech;
	}

	public void setYearsWithContactMech(Long yearsWithContactMech) {
		this.yearsWithContactMech = yearsWithContactMech;
	}

	public Long getMonthsWithContactMech() {
		return this.monthsWithContactMech;
	}

	public void setMonthsWithContactMech(Long monthsWithContactMech) {
		this.monthsWithContactMech = monthsWithContactMech;
	}

	public Date getLastUpdatedStamp() {
		return this.lastUpdatedStamp;
	}

	public void setLastUpdatedStamp(Date lastUpdatedStamp) {
		this.lastUpdatedStamp = lastUpdatedStamp;
	}

	public Date getLastUpdatedTxStamp() {
		return this.lastUpdatedTxStamp;
	}

	public void setLastUpdatedTxStamp(Date lastUpdatedTxStamp) {
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
	}

	public Date getCreatedStamp() {
		return this.createdStamp;
	}

	public void setCreatedStamp(Date createdStamp) {
		this.createdStamp = createdStamp;
	}

	public Date getCreatedTxStamp() {
		return this.createdTxStamp;
	}

	public void setCreatedTxStamp(Date createdTxStamp) {
		this.createdTxStamp = createdTxStamp;
	}

}