package com.apps.party.entitymodel;

import java.util.Date;

/**
 * Person generated by MyEclipse Persistence Tools
 */

public class Person extends com.magic.entitymodel.GenericEntity implements
		java.io.Serializable {

	// Fields

	private String partyId;

	private String salutation;

	private String firstName;

	private String middleName;

	private String lastName;

	private String personalTitle;

	private String suffix;

	private String nickname;

	private String firstNameLocal;

	private String middleNameLocal;

	private String lastNameLocal;

	private String otherLocal;

	private String memberId;

	private String gender;

	private Date birthDate;

	private Double height;

	private Double weight;

	private String mothersMaidenName;

	private String maritalStatus;

	private String socialSecurityNumber;

	private String passportNumber;

	private Date passportExpireDate;

	private Double totalYearsWorkExperience;

	private String comments;

	private String employmentStatusEnumId;

	private String residenceStatusEnumId;

	private String occupation;

	private Long yearsWithEmployer;

	private Long monthsWithEmployer;

	private String existingCustomer;

	private Date lastUpdatedStamp;

	private Date lastUpdatedTxStamp;

	private Date createdStamp;

	private Date createdTxStamp;

	// Constructors

	/** default constructor */
	public Person() {
	}

	/** minimal constructor */
	public Person(String partyId) {
		this.partyId = partyId;
	}

	/** full constructor */
	public Person(String partyId, String salutation, String firstName,
			String middleName, String lastName, String personalTitle,
			String suffix, String nickname, String firstNameLocal,
			String middleNameLocal, String lastNameLocal, String otherLocal,
			String memberId, String gender, Date birthDate, Double height,
			Double weight, String mothersMaidenName, String maritalStatus,
			String socialSecurityNumber, String passportNumber,
			Date passportExpireDate, Double totalYearsWorkExperience,
			String comments, String employmentStatusEnumId,
			String residenceStatusEnumId, String occupation,
			Long yearsWithEmployer, Long monthsWithEmployer,
			String existingCustomer, Date lastUpdatedStamp,
			Date lastUpdatedTxStamp, Date createdStamp, Date createdTxStamp) {
		this.partyId = partyId;
		this.salutation = salutation;
		this.firstName = firstName;
		this.middleName = middleName;
		this.lastName = lastName;
		this.personalTitle = personalTitle;
		this.suffix = suffix;
		this.nickname = nickname;
		this.firstNameLocal = firstNameLocal;
		this.middleNameLocal = middleNameLocal;
		this.lastNameLocal = lastNameLocal;
		this.otherLocal = otherLocal;
		this.memberId = memberId;
		this.gender = gender;
		this.birthDate = birthDate;
		this.height = height;
		this.weight = weight;
		this.mothersMaidenName = mothersMaidenName;
		this.maritalStatus = maritalStatus;
		this.socialSecurityNumber = socialSecurityNumber;
		this.passportNumber = passportNumber;
		this.passportExpireDate = passportExpireDate;
		this.totalYearsWorkExperience = totalYearsWorkExperience;
		this.comments = comments;
		this.employmentStatusEnumId = employmentStatusEnumId;
		this.residenceStatusEnumId = residenceStatusEnumId;
		this.occupation = occupation;
		this.yearsWithEmployer = yearsWithEmployer;
		this.monthsWithEmployer = monthsWithEmployer;
		this.existingCustomer = existingCustomer;
		this.lastUpdatedStamp = lastUpdatedStamp;
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
		this.createdStamp = createdStamp;
		this.createdTxStamp = createdTxStamp;
	}

	// Property accessors

	public String getPartyId() {
		return this.partyId;
	}

	public void setPartyId(String partyId) {
		this.partyId = partyId;
	}

	public String getSalutation() {
		return this.salutation;
	}

	public void setSalutation(String salutation) {
		this.salutation = salutation;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getPersonalTitle() {
		return this.personalTitle;
	}

	public void setPersonalTitle(String personalTitle) {
		this.personalTitle = personalTitle;
	}

	public String getSuffix() {
		return this.suffix;
	}

	public void setSuffix(String suffix) {
		this.suffix = suffix;
	}

	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	public String getFirstNameLocal() {
		return this.firstNameLocal;
	}

	public void setFirstNameLocal(String firstNameLocal) {
		this.firstNameLocal = firstNameLocal;
	}

	public String getMiddleNameLocal() {
		return this.middleNameLocal;
	}

	public void setMiddleNameLocal(String middleNameLocal) {
		this.middleNameLocal = middleNameLocal;
	}

	public String getLastNameLocal() {
		return this.lastNameLocal;
	}

	public void setLastNameLocal(String lastNameLocal) {
		this.lastNameLocal = lastNameLocal;
	}

	public String getOtherLocal() {
		return this.otherLocal;
	}

	public void setOtherLocal(String otherLocal) {
		this.otherLocal = otherLocal;
	}

	public String getMemberId() {
		return this.memberId;
	}

	public void setMemberId(String memberId) {
		this.memberId = memberId;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public Date getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	public Double getHeight() {
		return this.height;
	}

	public void setHeight(Double height) {
		this.height = height;
	}

	public Double getWeight() {
		return this.weight;
	}

	public void setWeight(Double weight) {
		this.weight = weight;
	}

	public String getMothersMaidenName() {
		return this.mothersMaidenName;
	}

	public void setMothersMaidenName(String mothersMaidenName) {
		this.mothersMaidenName = mothersMaidenName;
	}

	public String getMaritalStatus() {
		return this.maritalStatus;
	}

	public void setMaritalStatus(String maritalStatus) {
		this.maritalStatus = maritalStatus;
	}

	public String getSocialSecurityNumber() {
		return this.socialSecurityNumber;
	}

	public void setSocialSecurityNumber(String socialSecurityNumber) {
		this.socialSecurityNumber = socialSecurityNumber;
	}

	public String getPassportNumber() {
		return this.passportNumber;
	}

	public void setPassportNumber(String passportNumber) {
		this.passportNumber = passportNumber;
	}

	public Date getPassportExpireDate() {
		return this.passportExpireDate;
	}

	public void setPassportExpireDate(Date passportExpireDate) {
		this.passportExpireDate = passportExpireDate;
	}

	public Double getTotalYearsWorkExperience() {
		return this.totalYearsWorkExperience;
	}

	public void setTotalYearsWorkExperience(Double totalYearsWorkExperience) {
		this.totalYearsWorkExperience = totalYearsWorkExperience;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public String getEmploymentStatusEnumId() {
		return this.employmentStatusEnumId;
	}

	public void setEmploymentStatusEnumId(String employmentStatusEnumId) {
		this.employmentStatusEnumId = employmentStatusEnumId;
	}

	public String getResidenceStatusEnumId() {
		return this.residenceStatusEnumId;
	}

	public void setResidenceStatusEnumId(String residenceStatusEnumId) {
		this.residenceStatusEnumId = residenceStatusEnumId;
	}

	public String getOccupation() {
		return this.occupation;
	}

	public void setOccupation(String occupation) {
		this.occupation = occupation;
	}

	public Long getYearsWithEmployer() {
		return this.yearsWithEmployer;
	}

	public void setYearsWithEmployer(Long yearsWithEmployer) {
		this.yearsWithEmployer = yearsWithEmployer;
	}

	public Long getMonthsWithEmployer() {
		return this.monthsWithEmployer;
	}

	public void setMonthsWithEmployer(Long monthsWithEmployer) {
		this.monthsWithEmployer = monthsWithEmployer;
	}

	public String getExistingCustomer() {
		return this.existingCustomer;
	}

	public void setExistingCustomer(String existingCustomer) {
		this.existingCustomer = existingCustomer;
	}

	public Date getLastUpdatedStamp() {
		return this.lastUpdatedStamp;
	}

	public void setLastUpdatedStamp(Date lastUpdatedStamp) {
		this.lastUpdatedStamp = lastUpdatedStamp;
	}

	public Date getLastUpdatedTxStamp() {
		return this.lastUpdatedTxStamp;
	}

	public void setLastUpdatedTxStamp(Date lastUpdatedTxStamp) {
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
	}

	public Date getCreatedStamp() {
		return this.createdStamp;
	}

	public void setCreatedStamp(Date createdStamp) {
		this.createdStamp = createdStamp;
	}

	public Date getCreatedTxStamp() {
		return this.createdTxStamp;
	}

	public void setCreatedTxStamp(Date createdTxStamp) {
		this.createdTxStamp = createdTxStamp;
	}

}