package com.apps.party.entitymodel;

import java.util.Date;

/**
 * PostalAddress generated by MyEclipse Persistence Tools
 */

public class PostalAddress extends com.magic.entitymodel.GenericEntity
		implements java.io.Serializable {

	// Fields

	private String contactMechId;

	private String toName;

	private String attnName;

	private String address1;

	private String address2;

	private String directions;

	private String city;

	private String postalCode;

	private String postalCodeExt;

	private String countryGeoId;

	private String stateProvinceGeoId;

	private String countyGeoId;

	private String postalCodeGeoId;

	private String geoPointId;

	private Date lastUpdatedStamp;

	private Date lastUpdatedTxStamp;

	private Date createdStamp;

	private Date createdTxStamp;

	// Constructors

	/** default constructor */
	public PostalAddress() {
	}

	/** minimal constructor */
	public PostalAddress(String contactMechId) {
		this.contactMechId = contactMechId;
	}

	/** full constructor */
	public PostalAddress(String contactMechId, String toName, String attnName,
			String address1, String address2, String directions, String city,
			String postalCode, String postalCodeExt, String countryGeoId,
			String stateProvinceGeoId, String countyGeoId,
			String postalCodeGeoId, String geoPointId, Date lastUpdatedStamp,
			Date lastUpdatedTxStamp, Date createdStamp, Date createdTxStamp) {
		this.contactMechId = contactMechId;
		this.toName = toName;
		this.attnName = attnName;
		this.address1 = address1;
		this.address2 = address2;
		this.directions = directions;
		this.city = city;
		this.postalCode = postalCode;
		this.postalCodeExt = postalCodeExt;
		this.countryGeoId = countryGeoId;
		this.stateProvinceGeoId = stateProvinceGeoId;
		this.countyGeoId = countyGeoId;
		this.postalCodeGeoId = postalCodeGeoId;
		this.geoPointId = geoPointId;
		this.lastUpdatedStamp = lastUpdatedStamp;
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
		this.createdStamp = createdStamp;
		this.createdTxStamp = createdTxStamp;
	}

	// Property accessors

	public String getContactMechId() {
		return this.contactMechId;
	}

	public void setContactMechId(String contactMechId) {
		this.contactMechId = contactMechId;
	}

	public String getToName() {
		return this.toName;
	}

	public void setToName(String toName) {
		this.toName = toName;
	}

	public String getAttnName() {
		return this.attnName;
	}

	public void setAttnName(String attnName) {
		this.attnName = attnName;
	}

	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	public String getDirections() {
		return this.directions;
	}

	public void setDirections(String directions) {
		this.directions = directions;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	public String getPostalCodeExt() {
		return this.postalCodeExt;
	}

	public void setPostalCodeExt(String postalCodeExt) {
		this.postalCodeExt = postalCodeExt;
	}

	public String getCountryGeoId() {
		return this.countryGeoId;
	}

	public void setCountryGeoId(String countryGeoId) {
		this.countryGeoId = countryGeoId;
	}

	public String getStateProvinceGeoId() {
		return this.stateProvinceGeoId;
	}

	public void setStateProvinceGeoId(String stateProvinceGeoId) {
		this.stateProvinceGeoId = stateProvinceGeoId;
	}

	public String getCountyGeoId() {
		return this.countyGeoId;
	}

	public void setCountyGeoId(String countyGeoId) {
		this.countyGeoId = countyGeoId;
	}

	public String getPostalCodeGeoId() {
		return this.postalCodeGeoId;
	}

	public void setPostalCodeGeoId(String postalCodeGeoId) {
		this.postalCodeGeoId = postalCodeGeoId;
	}

	public String getGeoPointId() {
		return this.geoPointId;
	}

	public void setGeoPointId(String geoPointId) {
		this.geoPointId = geoPointId;
	}

	public Date getLastUpdatedStamp() {
		return this.lastUpdatedStamp;
	}

	public void setLastUpdatedStamp(Date lastUpdatedStamp) {
		this.lastUpdatedStamp = lastUpdatedStamp;
	}

	public Date getLastUpdatedTxStamp() {
		return this.lastUpdatedTxStamp;
	}

	public void setLastUpdatedTxStamp(Date lastUpdatedTxStamp) {
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
	}

	public Date getCreatedStamp() {
		return this.createdStamp;
	}

	public void setCreatedStamp(Date createdStamp) {
		this.createdStamp = createdStamp;
	}

	public Date getCreatedTxStamp() {
		return this.createdTxStamp;
	}

	public void setCreatedTxStamp(Date createdTxStamp) {
		this.createdTxStamp = createdTxStamp;
	}

}