package com.apps.party.entitymodel;

import java.util.Date;

/**
 * TelecomNumber generated by MyEclipse Persistence Tools
 */

public class TelecomNumber extends com.magic.entitymodel.GenericEntity
		implements java.io.Serializable {

	// Fields

	private String contactMechId;

	private String countryCode;

	private String areaCode;

	private String contactNumber;

	private String askForName;

	private Date lastUpdatedStamp;

	private Date lastUpdatedTxStamp;

	private Date createdStamp;

	private Date createdTxStamp;

	// Constructors

	/** default constructor */
	public TelecomNumber() {
	}

	/** minimal constructor */
	public TelecomNumber(String contactMechId) {
		this.contactMechId = contactMechId;
	}

	/** full constructor */
	public TelecomNumber(String contactMechId, String countryCode,
			String areaCode, String contactNumber, String askForName,
			Date lastUpdatedStamp, Date lastUpdatedTxStamp, Date createdStamp,
			Date createdTxStamp) {
		this.contactMechId = contactMechId;
		this.countryCode = countryCode;
		this.areaCode = areaCode;
		this.contactNumber = contactNumber;
		this.askForName = askForName;
		this.lastUpdatedStamp = lastUpdatedStamp;
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
		this.createdStamp = createdStamp;
		this.createdTxStamp = createdTxStamp;
	}

	// Property accessors

	public String getContactMechId() {
		return this.contactMechId;
	}

	public void setContactMechId(String contactMechId) {
		this.contactMechId = contactMechId;
	}

	public String getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

	public String getAreaCode() {
		return this.areaCode;
	}

	public void setAreaCode(String areaCode) {
		this.areaCode = areaCode;
	}

	public String getContactNumber() {
		return this.contactNumber;
	}

	public void setContactNumber(String contactNumber) {
		this.contactNumber = contactNumber;
	}

	public String getAskForName() {
		return this.askForName;
	}

	public void setAskForName(String askForName) {
		this.askForName = askForName;
	}

	public Date getLastUpdatedStamp() {
		return this.lastUpdatedStamp;
	}

	public void setLastUpdatedStamp(Date lastUpdatedStamp) {
		this.lastUpdatedStamp = lastUpdatedStamp;
	}

	public Date getLastUpdatedTxStamp() {
		return this.lastUpdatedTxStamp;
	}

	public void setLastUpdatedTxStamp(Date lastUpdatedTxStamp) {
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
	}

	public Date getCreatedStamp() {
		return this.createdStamp;
	}

	public void setCreatedStamp(Date createdStamp) {
		this.createdStamp = createdStamp;
	}

	public Date getCreatedTxStamp() {
		return this.createdTxStamp;
	}

	public void setCreatedTxStamp(Date createdTxStamp) {
		this.createdTxStamp = createdTxStamp;
	}

}